from typing import TypeVar

from tbot.clients.walletapp.enums.categories import Category, SubCategoryFood

MCCCodeCategory = {
    5411: (Category.FOOD, SubCategoryFood.GROCERIES),
    742: "VETERINARY_SERVICES",
    763: "AGRICULTURAL_CO_OPERATIVES",
    780: "HORTICULTURAL_SERVICES_LANDSCAPING",
    1520: "GENERAL_CONTRACTORS_RESIDENTIAL",
    1711: "AIR_CONDITIONING_CONTRACTORS",
    1731: "ELECTRICAL_CONTRACTORS",
    1740: "INSULATION_CONTRACTORS",
    1750: "CARPENTRY_CONTRACTORS",
    1761: "ROOFING_CONTRACTORS",
    1771: "CONTRACTORS_CONCRETE",
    1799: "CONTRACTORS_SPECIAL",
    2741: "MISCELLANEOUS_PUBLISHING_AND",
    2791: "TYPESETTING_PLATE_MAKING",
    2842: "SPECIALTY_CLEANING_POLISHING",
    3000: "UNITED_AIRLINES",
    3001: "AMERICAN_AIRLINES",
    3002: "PAN_AMERICAN",
    3003: "AIRLINES",
    3004: "TRANS_WORLD_AIRLINES",
    3005: "BRITISH_AIRWAYS",
    3006: "JAPAN_AIRLINES",
    3007: "AIR_FRANCE",
    3008: "LUFTHANSA",
    3009: "AIR_CANADA",
    3010: "KLM_ROYAL_DUTCH",
    3011: "AEORFLOT",
    3012: "QANTAS",
    3013: "ALITALIA",
    3014: "SAUDIA_ARABIAN_AIRLINES",
    3015: "SWISSAIR",
    3016: "SAS",
    3017: "SOUTH_AFRICAN_AIRWAYS",
    3018: "VARIG_BRAZIL",
    3019: "AIRLINES",
    3020: "AIR_INDIA",
    3021: "AIR_ALGERIE",
    3022: "PHILIPPINE_AIRLINES",
    3023: "MEXICANA",
    3024: "PAKISTAN_INTERNATIONAL",
    3025: "AIR_NEW_ZEALAND",
    3026: "AIRLINES",
    3027: "UTA_INTERAIR",
    3028: "AIR_MALTA",
    3029: "SABENA",
    3030: "AEROLINEAS_ARGENTINAS",
    3031: "OLYMPIC_AIRWAYS",
    3032: "EL_AL",
    3033: "ANSETT_AIRLINES",
    3034: "AUSTRAINLIAN_AIRLINES",
    3035: "TAP_PORTUGAL",
    3036: "VASP_BRAZIL",
    3037: "EGYPTAIR",
    3038: "KUWAIT_AIRLINES",
    3039: "AVIANCA",
    3040: "GULF_AIR_BAHRAIN",
    3041: "BALKAN_BULGARIAN_AIRLINES",
    3042: "FINNAIR",
    3043: "AER_LINGUS",
    3044: "AIR_LANKA",
    3045: "NIGERIA_AIRWAYS",
    3046: "CRUZEIRO_DO_SUL",
    3047: "THY_TURKEY",
    3048: "ROYAL_AIR_MAROC",
    3049: "TUNIS_AIR",
    3050: "ICELANDAIR",
    3051: "AUSTRIAN_AIRLINES",
    3052: "LANCHILE",
    3053: "AVIACO_SPAIN",
    3054: "LADECO_CHILE",
    3055: "LAB_BOLIVIA",
    3056: "QUEBECAIRE",
    3057: "EASTWEST_AIRLINES_AUSTRALIA",
    3058: "DELTA",
    3059: "AIRLINES",
    3060: "NORTHWEST",
    3061: "CONTINENTAL",
    3062: "WESTERN",
    3063: "US_AIR",
    3064: "AIRLINES",
    3065: "AIRINTER",
    3066: "SOUTHWEST",
    3067: "AIRLINES",
    3068: "AIRLINES",
    3069: "SUN_COUNTRY_AIRLINES",
    3070: "AIRLINES",
    3071: "AIR_BRITISH_COLUBIA",
    3072: "AIRLINES",
    3073: "AIRLINES",
    3074: "AIRLINES",
    3075: "SINGAPORE_AIRLINES",
    3076: "AEROMEXICO",
    3077: "THAI_AIRWAYS",
    3078: "CHINA_AIRLINES",
    3079: "AIRLINES",
    3080: "AIRLINES",
    3081: "NORDAIR",
    3082: "KOREAN_AIRLINES",
    3083: "AIR_AFRIGUE",
    3084: "EVA_AIRLINES",
    3085: "MIDWEST_EXPRESS_AIRLINES",
    3086: "AIRLINES",
    3087: "METRO_AIRLINES",
    3088: "CROATIA_AIRLINES",
    3089: "TRANSAERO",
    3090: "AIRLINES",
    3091: "AIRLINES",
    3092: "AIRLINES",
    3093: "AIRLINES",
    3094: "ZAMBIA_AIRWAYS",
    3095: "AIRLINES",
    3096: "AIR_ZIMBABWE",
    3097: "AIRLINES",
    3098: "AIRLINES",
    3099: "CATHAY_PACIFIC",
    3100: "MALAYSIAN_AIRLINE_SYSTEM",
    3101: "AIRLINES",
    3102: "IBERIA",
    3103: "GARUDA_INDONESIA",
    3104: "AIRLINES",
    3105: "AIRLINES",
    3106: "BRAATHENS_SAFE_NORWAY",
    3107: "AIRLINES",
    3108: "AIRLINES",
    3109: "AIRLINES",
    3110: "WINGS_AIRWAYS",
    3111: "BRITISH_MIDLAND",
    3112: "WINDWARD_ISLAND",
    3113: "AIRLINES",
    3114: "AIRLINES",
    3115: "AIRLINES",
    3116: "AIRLINES",
    3117: "VIASA",
    3118: "VALLEY_AIRLINES",
    3119: "AIRLINES",
    3120: "AIRLINES",
    3121: "AIRLINES",
    3122: "AIRLINES",
    3123: "AIRLINES",
    3124: "AIRLINES",
    3125: "TAN",
    3126: "TALAIR",
    3127: "TACA_INTERNATIONAL",
    3128: "AIRLINES",
    3129: "SURINAM_AIRWAYS",
    3130: "SUN_WORLD_INTERNATIONAL",
    3131: "AIRLINES",
    3132: "AIRLINES",
    3133: "SUNBELT_AIRLINES",
    3134: "AIRLINES",
    3135: "SUDAN_AIRWAYS",
    3136: "AIRLINES",
    3137: "SINGLETON",
    3138: "SIMMONS_AIRLINES",
    3139: "AIRLINES",
    3140: "AIRLINES",
    3141: "AIRLINES",
    3142: "AIRLINES",
    3143: "SCENIC_AIRLINES",
    3144: "VIRGIN_ATLANTIC",
    3145: "SAN_JUAN_AIRLINES",
    3146: "LUXAIR",
    3147: "AIRLINES",
    3148: "AIRLINES",
    3149: "AIRLINES",
    3150: "AIRLINES",
    3151: "AIR_ZAIRE",
    3152: "AIRLINES",
    3153: "AIRLINES",
    3154: "PRINCEVILLE",
    3155: "AIRLINES",
    3156: "AIRLINES",
    3157: "AIRLINES",
    3158: "AIRLINES",
    3159: "PBA",
    3160: "AIRLINES",
    3161: "ALL_NIPPON_AIRWAYS",
    3162: "AIRLINES",
    3163: "AIRLINES",
    3164: "NORONTAIR",
    3165: "NEW_YORK_HELICOPTER",
    3166: "AIRLINES",
    3167: "AIRLINES",
    3168: "AIRLINES",
    3169: "AIRLINES",
    3170: "NOUNT_COOK",
    3171: "CANADIAN_AIRLINES_INTERNATIONAL",
    3172: "NATIONAIR",
    3173: "AIRLINES",
    3174: "AIRLINES",
    3175: "AIRLINES",
    3176: "METROFLIGHT_AIRLINES",
    3177: "AIRLINES",
    3178: "MESA_AIR",
    3179: "AIRLINES",
    3180: "AIRLINES",
    3181: "MALEV",
    3182: "LOT_POLAND",
    3183: "AIRLINES",
    3184: "LIAT",
    3185: "LAV_VENEZUELA",
    3186: "LAP_PARAGUAY",
    3187: "LACSA_COSTA_RICA",
    3188: "AIRLINES",
    3189: "AIRLINES",
    3190: "JUGOSLAV_AIR",
    3191: "ISLAND_AIRLINES",
    3192: "IRAN_AIR",
    3193: "INDIAN_AIRLINES",
    3194: "AIRLINES",
    3195: "AIRLINES",
    3196: "HAWAIIAN_AIR",
    3197: "HAVASU_AIRLINES",
    3198: "AIRLINES",
    3199: "AIRLINES",
    3200: "FUYANA_AIRWAYS",
    3201: "AIRLINES",
    3202: "AIRLINES",
    3203: "GOLDEN_PACIFIC_AIR",
    3204: "FREEDOM_AIR",
    3205: "AIRLINES",
    3206: "AIRLINES",
    3207: "AIRLINES",
    3208: "AIRLINES",
    3209: "AIRLINES",
    3210: "AIRLINES",
    3211: "AIRLINES",
    3212: "DOMINICANA",
    3213: "AIRLINES",
    3214: "AIRLINES",
    3215: "DAN_AIR_SERVICES",
    3216: "CUMBERLAND_AIRLINES",
    3217: "CSA",
    3218: "CROWN_AIR",
    3219: "COPA",
    3220: "COMPANIA_FAUCETT",
    3221: "TRANSPORTES_AEROS_MILITARES",
    3222: "COMMAND_AIRWAYS",
    3223: "COMAIR",
    3224: "AIRLINES",
    3225: "AIRLINES",
    3226: "AIRLINES",
    3227: "AIRLINES",
    3228: "CAYMAN_AIRWAYS",
    3229: "SAETA_SOCIAEDAD_ECUATORIANOS",
    3230: "AIRLINES",
    3231: "SASHA_SERVICIO_AERO",
    3232: "AIRLINES",
    3233: "CAPITOL_AIR",
    3234: "BWIA",
    3235: "BROKWAY_AIR",
    3236: "AIRLINES",
    3237: "AIRLINES",
    3238: "BEMIDJI_AIRLINES",
    3239: "BAR_HARBOR_AIRLINES",
    3240: "BAHAMASAIR",
    3241: "AVIATECA_GUATEMALA",
    3242: "AVENSA",
    3243: "AUSTRIAN_AIR_SERVICE",
    3244: "AIRLINES",
    3245: "AIRLINES",
    3246: "AIRLINES",
    3247: "AIRLINES",
    3248: "AIRLINES",
    3249: "AIRLINES",
    3250: "AIRLINES",
    3251: "ALOHA_AIRLINES",
    3252: "ALM",
    3253: "AMERICA_WEST",
    3254: "TRUMP_AIRLINE",
    3255: "AIRLINES",
    3256: "ALASKA_AIRLINES",
    3257: "AIRLINES",
    3258: "AIRLINES",
    3259: "AMERICAN_TRANS_AIR",
    3260: "AIRLINES",
    3261: "AIR_CHINA",
    3262: "RENO_AIR_INC",
    3263: "AIRLINES",
    3264: "AIRLINES",
    3265: "AIRLINES",
    3266: "AIR_SEYCHELLES",
    3267: "AIR_PANAMA",
    3268: "AIRLINES",
    3269: "AIRLINES",
    3270: "AIRLINES",
    3271: "AIRLINES",
    3272: "AIRLINES",
    3273: "AIRLINES",
    3274: "AIRLINES",
    3275: "AIRLINES",
    3276: "AIRLINES",
    3277: "AIRLINES",
    3278: "AIRLINES",
    3279: "AIRLINES",
    3280: "AIR_JAMAICA",
    3281: "AIRLINES",
    3282: "AIR_DJIBOUTI",
    3283: "AIRLINES",
    3284: "AERO_VIRGIN_ISLANDS",
    3285: "AERO_PERU",
    3286: "AEROLINEAS_NICARAGUENSIS",
    3287: "AERO_COACH_AVAIATION",
    3288: "AIRLINES",
    3289: "AIRLINES",
    3290: "AIRLINES",
    3291: "ARIANA_AFGHAN",
    3292: "CYPRUS_AIRWAYS",
    3293: "ECUATORIANA",
    3294: "ETHIOPIAN_AIRLINES",
    3295: "KENYA_AIRLINES",
    3296: "AIRLINES",
    3297: "AIRLINES",
    3298: "AIR_MAURITIUS",
    3299: "WIDEROS_FLYVESELSKAP",
    3351: "AFFILIATED_AUTO_RENTAL",
    3352: "AMERICAN_INTL_RENT",
    3353: "BROOKS_RENT_A",
    3354: "ACTION_AUTO_RENTAL",
    3355: "CAR_RENTAL",
    3356: "CAR_RENTAL",
    3357: "HERTZ_RENT_A",
    3358: "CAR_RENTAL",
    3359: "PAYLESS_CAR_RENTAL",
    3360: "SNAPPY_CAR_RENTAL",
    3361: "AIRWAYS_RENT_A",
    3362: "ALTRA_AUTO_RENTAL",
    3363: "CAR_RENTAL",
    3364: "AGENCY_RENT_A",
    3365: "CAR_RENTAL",
    3366: "BUDGET_RENT_A",
    3367: "CAR_RENTAL",
    3368: "HOLIDAY_RENT_A",
    3369: "CAR_RENTAL",
    3370: "RENT_A_WRECK",
    3371: "CAR_RENTAL",
    3372: "CAR_RENTAL",
    3373: "CAR_RENTAL",
    3374: "CAR_RENTAL",
    3375: "CAR_RENTAL",
    3376: "AJAX_RENT_A",
    3377: "CAR_RENTAL",
    3378: "CAR_RENTAL",
    3379: "CAR_RENTAL",
    3380: "CAR_RENTAL",
    3381: "EUROP_CAR",
    3382: "CAR_RENTAL",
    3383: "CAR_RENTAL",
    3384: "CAR_RENTAL",
    3385: "TROPICAL_RENT_A",
    3386: "SHOWCASE_RENTAL_CARS",
    3387: "ALAMO_RENT_A",
    3388: "CAR_RENTAL",
    3389: "AVIS_RENT_A",
    3390: "DOLLAR_RENT_A",
    3391: "EUROPE_BY_CAR",
    3392: "CAR_RENTAL",
    3393: "NATIONAL_CAR_RENTAL",
    3394: "KEMWELL_GROUP_RENT",
    3395: "THRIFTY_RENT_A",
    3396: "TILDEN_TENT_A",
    3397: "CAR_RENTAL",
    3398: "ECONO_CAR_RENT",
    3399: "CAR_RENTAL",
    3400: "AUTO_HOST_COST",
    3401: "CAR_RENTAL",
    3402: "CAR_RENTAL",
    3403: "CAR_RENTAL",
    3404: "CAR_RENTAL",
    3405: "ENTERPRISE_RENT_A",
    3406: "CAR_RENTAL",
    3407: "CAR_RENTAL",
    3408: "CAR_RENTAL",
    3409: "GENERAL_RENT_A",
    3410: "CAR_RENTAL",
    3411: "CAR_RENTAL",
    3412: "A_1_RENT",
    3413: "CAR_RENTAL",
    3414: "GODFREY_NATL_RENT",
    3415: "CAR_RENTAL",
    3416: "CAR_RENTAL",
    3417: "CAR_RENTAL",
    3418: "CAR_RENTAL",
    3419: "ALPHA_RENT_A",
    3420: "ANSA_INTL_RENT",
    3421: "ALLSTAE_RENT_A",
    3422: "CAR_RENTAL",
    3423: "AVCAR_RENT_A",
    3424: "CAR_RENTAL",
    3425: "AUTOMATE_RENT_A",
    3426: "CAR_RENTAL",
    3427: "AVON_RENT_A",
    3428: "CAREY_RENT_A",
    3429: "INSURANCE_RENT_A",
    3430: "MAJOR_RENT_A",
    3431: "REPLACEMENT_RENT_A",
    3432: "RESERVE_RENT_A",
    3433: "UGLY_DUCKLING_RENT",
    3434: "USA_RENT_A",
    3435: "VALUE_RENT_A",
    3436: "AUTOHANSA_RENT_A",
    3437: "CITE_RENT_A",
    3438: "INTERENT_RENT_A",
    3439: "MILLEVILLE_RENT_A",
    3440: "VIA_ROUTE_RENT",
    3441: "CAR_RENTAL",
    3501: "HOLIDAY_INNS_HOLIDAY",
    3502: "BEST_WESTERN_HOTELS",
    3503: "SHERATON_HOTELS",
    3504: "HILTON_HOTELS",
    3505: "FORTE_HOTELS",
    3506: "GOLDEN_TULIP_HOTELS",
    3507: "FRIENDSHIP_INNS",
    3508: "QUALITY_INNS_QUALITY",
    3509: "MARRIOTT_HOTELS",
    3510: "DAYS_INN_DAYSTOP",
    3511: "ARABELLA_HOTELS",
    3512: "INTER_CONTINENTAL_HOTELS",
    3513: "WESTIN_HOTELS",
    3514: "HOTELS_MOTELS_INNS_RESORTS",
    3515: "RODEWAY_INNS",
    3516: "LA_QUINTA_MOTOR",
    3517: "AMERICANA_HOTELS",
    3518: "SOL_HOTELS",
    3519: "PULLMAN_INTERNATIONAL_HOTELS",
    3520: "MERIDIEN_HOTELS",
    3521: "CREST_HOTELS_SEE",
    3522: "TOKYO_HOTEL",
    3523: "PENNSULA_HOTEL",
    3524: "WELCOMGROUP_HOTELS",
    3525: "DUNFEY_HOTELS",
    3526: "HOTELS_MOTELS_INNS_RESORTS",
    3527: "DOWNTOWNER_PASSPORT_HOTEL",
    3528: "RED_LION_HOTELS",
    3529: "CP_HOTELS",
    3530: "RENAISSANCE_HOTELS_STOUFFER",
    3531: "ASTIR_HOTELS",
    3532: "SUN_ROUTE_HOTELS",
    3533: "HOTEL_IBIS",
    3534: "SOUTHERN_PACIFIC_HOTELS",
    3535: "HILTON_INTERNATIONAL",
    3536: "AMFAC_HOTELS",
    3537: "ANA_HOTEL",
    3538: "CONCORDE_HOTELS",
    3539: "HOTELS_MOTELS_INNS_RESORTS",
    3540: "IBEROTEL_HOTELS",
    3541: "HOTEL_OKURA",
    3542: "ROYAL_HOTELS",
    3543: "FOUR_SEASONS_HOTELS",
    3544: "CIGA_HOTELS",
    3545: "SHANGRI_LA_INTERNATIONAL",
    3546: "HOTELS_MOTELS_INNS_RESORTS",
    3547: "HOTELS_MOTELS_INNS_RESORTS",
    3548: "HOTELES_MELIA",
    3549: "AUBERGE_DES_GOVERNEURS",
    3550: "REGAL_8_INNS",
    3551: "HOTELS_MOTELS_INNS_RESORTS",
    3552: "COAST_HOTELS",
    3553: "PARK_INNS_INTERNATIONAL",
    3554: "HOTELS_MOTELS_INNS_RESORTS",
    3555: "HOTELS_MOTELS_INNS_RESORTS",
    3556: "HOTELS_MOTELS_INNS_RESORTS",
    3557: "HOTELS_MOTELS_INNS_RESORTS",
    3558: "JOLLY_HOTELS",
    3559: "HOTELS_MOTELS_INNS_RESORTS",
    3560: "HOTELS_MOTELS_INNS_RESORTS",
    3561: "HOTELS_MOTELS_INNS_RESORTS",
    3562: "COMFORT_INNS",
    3563: "JOURNEYS_END_MOTLS",
    3564: "HOTELS_MOTELS_INNS_RESORTS",
    3565: "RELAX_INNS",
    3566: "HOTELS_MOTELS_INNS_RESORTS",
    3567: "HOTELS_MOTELS_INNS_RESORTS",
    3568: "LADBROKE_HOTELS",
    3569: "HOTELS_MOTELS_INNS_RESORTS",
    3570: "FORUM_HOTELS",
    3571: "HOTELS_MOTELS_INNS_RESORTS",
    3572: "MIYAKO_HOTELS",
    3573: "SANDMAN_HOTELS",
    3574: "VENTURE_INNS",
    3575: "VAGABOND_HOTELS",
    3576: "HOTELS_MOTELS_INNS_RESORTS",
    3577: "MANDARIN_ORIENTAL_HOTEL",
    3578: "HOTELS_MOTELS_INNS_RESORTS",
    3579: "HOTEL_MERCURE",
    3580: "HOTELS_MOTELS_INNS_RESORTS",
    3581: "DELTA_HOTEL",
    3582: "HOTELS_MOTELS_INNS_RESORTS",
    3583: "SAS_HOTELS",
    3584: "PRINCESS_HOTELS_INTERNATIONAL",
    3585: "HUNGAR_HOTELS",
    3586: "SOKOS_HOTELS",
    3587: "DORAL_HOTELS",
    3588: "HELMSLEY_HOTELS",
    3589: "HOTELS_MOTELS_INNS_RESORTS",
    3590: "FAIRMONT_HOTELS",
    3591: "SONESTA_HOTELS",
    3592: "OMNI_HOTELS",
    3593: "CUNARD_HOTELS",
    3594: "HOTELS_MOTELS_INNS_RESORTS",
    3595: "HOSPITALITY_INTERNATIONAL",
    3596: "HOTELS_MOTELS_INNS_RESORTS",
    3597: "HOTELS_MOTELS_INNS_RESORTS",
    3598: "REGENT_INTERNATIONAL_HOTELS",
    3599: "PANNONIA_HOTELS",
    3600: "HOTELS_MOTELS_INNS_RESORTS",
    3601: "HOTELS_MOTELS_INNS_RESORTS",
    3602: "HOTELS_MOTELS_INNS_RESORTS",
    3603: "NOAHS_HOTELS",
    3604: "HOTELS_MOTELS_INNS_RESORTS",
    3605: "HOTELS_MOTELS_INNS_RESORTS",
    3606: "HOTELS_MOTELS_INNS_RESORTS",
    3607: "HOTELS_MOTELS_INNS_RESORTS",
    3608: "HOTELS_MOTELS_INNS_RESORTS",
    3609: "HOTELS_MOTELS_INNS_RESORTS",
    3610: "HOTELS_MOTELS_INNS_RESORTS",
    3611: "HOTELS_MOTELS_INNS_RESORTS",
    3612: "MOVENPICK_HOTELS",
    3613: "HOTELS_MOTELS_INNS_RESORTS",
    3614: "HOTELS_MOTELS_INNS_RESORTS",
    3615: "TRAVELODGE",
    3616: "HOTELS_MOTELS_INNS_RESORTS",
    3617: "HOTELS_MOTELS_INNS_RESORTS",
    3618: "HOTELS_MOTELS_INNS_RESORTS",
    3619: "HOTELS_MOTELS_INNS_RESORTS",
    3620: "TELFORD_INTERNATIONAL",
    3621: "HOTELS_MOTELS_INNS_RESORTS",
    3622: "MERLIN_HOTELS",
    3623: "DORINT_HOTELS",
    3624: "HOTELS_MOTELS_INNS_RESORTS",
    3625: "HOTLE_UNIVERSALE",
    3626: "PRINCE_HOTELS",
    3627: "HOTELS_MOTELS_INNS_RESORTS",
    3628: "HOTELS_MOTELS_INNS_RESORTS",
    3629: "DAN_HOTELS",
    3630: "HOTELS_MOTELS_INNS_RESORTS",
    3631: "HOTELS_MOTELS_INNS_RESORTS",
    3632: "HOTELS_MOTELS_INNS_RESORTS",
    3633: "RANK_HOTELS",
    3634: "SWISSOTEL",
    3635: "RESO_HOTELS",
    3636: "SAROVA_HOTELS",
    3637: "RAMADA_INNS_RAMADA",
    3638: "HO_JO_INN",
    3639: "MOUNT_CHARLOTTE_THISTLE",
    3640: "HYATT_HOTEL",
    3641: "SOFITEL_HOTELS",
    3642: "NOVOTEL_HOTELS",
    3643: "STEIGENBERGER_HOTELS",
    3644: "ECONO_LODGES",
    3645: "QUEENS_MOAT_HOUSES",
    3646: "SWALLOW_HOTELS",
    3647: "HUSA_HOTELS",
    3648: "DE_VERE_HOTELS",
    3649: "RADISSON_HOTELS",
    3650: "RED_ROOK_INNS",
    3651: "IMPERIAL_LONDON_HOTEL",
    3652: "EMBASSY_HOTELS",
    3653: "PENTA_HOTELS",
    3654: "LOEWS_HOTELS",
    3655: "SCANDIC_HOTELS",
    3656: "SARA_HOTELS",
    3657: "OBEROI_HOTELS",
    3658: "OTANI_HOTELS",
    3659: "TAJ_HOTELS_INTERNATIONAL",
    3660: "KNIGHTS_INNS",
    3661: "METROPOLE_HOTELS",
    3662: "HOTELS_MOTELS_INNS_RESORTS",
    3663: "HOTELES_EL_PRESIDENTS",
    3664: "FLAG_INN",
    3665: "HAMPTON_INNS",
    3666: "STAKIS_HOTELS",
    3667: "HOTELS_MOTELS_INNS_RESORTS",
    3668: "MARITIM_HOTELS",
    3669: "HOTELS_MOTELS_INNS_RESORTS",
    3670: "ARCARD_HOTELS",
    3671: "ARCTIA_HOTELS",
    3672: "CAMPANIEL_HOTELS",
    3673: "IBUSZ_HOTELS",
    3674: "RANTASIPI_HOTELS",
    3675: "INTERHOTEL_CEDOK",
    3676: "HOTELS_MOTELS_INNS_RESORTS",
    3677: "CLIMAT_DE_FRANCE",
    3678: "CUMULUS_HOTELS",
    3679: "DANUBIUS_HOTEL",
    3680: "HOTELS_MOTELS_INNS_RESORTS",
    3681: "ADAMS_MARK_HOTELS",
    3682: "ALLSTAR_INNS",
    3683: "HOTELS_MOTELS_INNS_RESORTS",
    3684: "BUDGET_HOST_INNS",
    3685: "BUDGETEL_HOTELS",
    3686: "SUISSE_CHALETS",
    3687: "CLARION_HOTELS",
    3688: "COMPRI_HOTELS",
    3689: "CONSORT_HOTELS",
    3690: "COURTYARD_BY_MARRIOTT",
    3691: "DILLION_INNS",
    3692: "DOUBLETREE_HOTELS",
    3693: "DRURY_INNS",
    3694: "ECONOMY_INNS_OF",
    3695: "EMBASSY_SUITES",
    3696: "EXEL_INNS",
    3697: "FARFIELD_HOTELS",
    3698: "HARLEY_HOTELS",
    3699: "MIDWAY_MOTOR_LODGE",
    3700: "MOTEL_6",
    3701: "GUEST_QUARTERS_FORMALLY",
    3702: "THE_REGISTRY_HOTELS",
    3703: "RESIDENCE_INNS",
    3704: "ROYCE_HOTELS",
    3705: "SANDMAN_INNS",
    3706: "SHILO_INNS",
    3707: "SHONEYS_INNS",
    3708: "HOTELS_MOTELS_INNS_RESORTS",
    3709: "SUPER8_MOTELS",
    3710: "THE_RITZ_CARLTON",
    3711: "FLAG_INNS_AUSRALIA",
    3712: "GOLDEN_CHAIN_HOTEL",
    3713: "QUALITY_PACIFIC_HOTEL",
    3714: "FOUR_SEASONS_HOTEL",
    3715: "FARIFIELD_INN",
    3716: "CARLTON_HOTELS",
    3717: "CITY_LODGE_HOTELS",
    3718: "KAROS_HOTELS",
    3719: "PROTEA_HOTELS",
    3720: "SOUTHERN_SUN_HOTELS",
    3721: "HILTON_CONRAD",
    3722: "WYNDHAM_HOTEL_AND",
    3723: "RICA_HOTELS",
    3724: "INER_NOR_HOTELS",
    3725: "SEAINES_PLANATION",
    3726: "RIO_SUITES",
    3727: "BROADMOOR_HOTEL",
    3728: "BALLYS_HOTEL_AND",
    3729: "JOHN_ASCUAGAS_NUGGET",
    3730: "MGM_GRAND_HOTEL",
    3731: "HARRAHS_HOTELS_AND",
    3732: "OPRYLAND_HOTEL",
    3733: "BOCA_RATON_RESORT",
    3734: "HARVEY_BRISTOL_HOTELS",
    3735: "HOTELS_MOTELS_INNS_RESORTS",
    3736: "COLORADO_BELLE_EDGEWATER_RESORT",
    3737: "RIVIERA_HOTEL_AND",
    3738: "TROPICANA_RESORT_AND",
    3739: "WOODSIDE_HOTELS_AND",
    3740: "TOWNPLACE_SUITES",
    3741: "MILLENIUM_BROADWAY_HOTEL",
    3742: "CLUB_MED",
    3743: "BILTMORE_HOTEL_AND",
    3744: "CAREFREE_RESORTS",
    3745: "ST_REGIS_HOTEL",
    3746: "THE_ELIOT_HOTEL",
    3747: "CLUBCORP_CLUB_RESORTS",
    3748: "WELESLEY_INNS",
    3749: "THE_BEVERLY_HILLS",
    3750: "CROWNE_PLAZA_HOTELS",
    3751: "HOMEWOOD_SUITES",
    3752: "PEABODY_HOTELS",
    3753: "GREENBRIAH_RESORTS",
    3754: "AMELIA_ISLAND_PLANATION",
    3755: "THE_HOMESTEAD",
    3756: "SOUTH_SEAS_RESORTS",
    3757: "HOTELS_MOTELS_INNS_RESORTS",
    3758: "HOTELS_MOTELS_INNS_RESORTS",
    3759: "HOTELS_MOTELS_INNS_RESORTS",
    3760: "HOTELS_MOTELS_INNS_RESORTS",
    3761: "HOTELS_MOTELS_INNS_RESORTS",
    3762: "HOTELS_MOTELS_INNS_RESORTS",
    3763: "HOTELS_MOTELS_INNS_RESORTS",
    3764: "HOTELS_MOTELS_INNS_RESORTS",
    3765: "HOTELS_MOTELS_INNS_RESORTS",
    3766: "HOTELS_MOTELS_INNS_RESORTS",
    3767: "HOTELS_MOTELS_INNS_RESORTS",
    3768: "HOTELS_MOTELS_INNS_RESORTS",
    3769: "HOTELS_MOTELS_INNS_RESORTS",
    3770: "HOTELS_MOTELS_INNS_RESORTS",
    3771: "HOTELS_MOTELS_INNS_RESORTS",
    3772: "HOTELS_MOTELS_INNS_RESORTS",
    3773: "HOTELS_MOTELS_INNS_RESORTS",
    3774: "HOTELS_MOTELS_INNS_RESORTS",
    3775: "HOTELS_MOTELS_INNS_RESORTS",
    3776: "HOTELS_MOTELS_INNS_RESORTS",
    3777: "HOTELS_MOTELS_INNS_RESORTS",
    3778: "HOTELS_MOTELS_INNS_RESORTS",
    3779: "HOTELS_MOTELS_INNS_RESORTS",
    3780: "HOTELS_MOTELS_INNS_RESORTS",
    3781: "HOTELS_MOTELS_INNS_RESORTS",
    3782: "HOTELS_MOTELS_INNS_RESORTS",
    3783: "HOTELS_MOTELS_INNS_RESORTS",
    3784: "HOTELS_MOTELS_INNS_RESORTS",
    3785: "HOTELS_MOTELS_INNS_RESORTS",
    3786: "HOTELS_MOTELS_INNS_RESORTS",
    3787: "HOTELS_MOTELS_INNS_RESORTS",
    3788: "HOTELS_MOTELS_INNS_RESORTS",
    3789: "HOTELS_MOTELS_INNS_RESORTS",
    3790: "HOTELS_MOTELS_INNS_RESORTS",
    3816: "HOME2SUITES",
    3835: "MASTERS_ECONOMY_INNS",
    4011: "RAILROADS",
    4111: "LOCAL_SUBURBAN_COMMUTER_PASSENGER",
    4112: "PASSENGER_RAILWAYS",
    4119: "AMBULANCE_SERVICES",
    4121: "TAXICABS_AND_LIMOUSINES",
    4131: "BUS_LINES_INCLUDING",
    4214: "MOTOR_FREIGHT_CARRIERS",
    4215: "COURIER_SERVICES",
    4225: "PUBLIC_WAREHOUSING_STORAGE",
    4411: "CRUISE_AND_STEAMSHIP",
    4457: "BOAT_RENTALS_AND",
    4468: "MARINAS_MARINE_SERVICE",
    4511: "AIRLINES_AIR_CARRIERS",
    4582: "AIRPORTS_AIRPORT_TERMINALS",
    4722: "TRAVEL_AGENCIES_AND",
    4723: "PACKAGE_TOUR_OPERATORS",
    4784: "TOLL_AND_BRIDGE",
    4789: "TRANSPORTATION_SERVICES_NOT",
    4812: "TELECOMMUNICATIONS_EQUIPMENT_INCLUDING",
    4814: "FAX_SERVICES_TELECOMMUNICATION",
    4815: "VISAPHONE",
    4816: "COMPUTER_NETWORK_SERVICES",
    4821: "TELEGRAPH_SERVICES",
    4829: "MONEY_ORDERS",
    4899: "CABLE_AND_OTHER",
    4900: "ELECTRIC_GAS_SANITARY",
    5013: "MOTOR_VEHICLE_SUPPLIES",
    5021: "OFFICE_AND_COMMERCIAL",
    5039: "CONSTRUCTION_MATERIALS_NOT",
    5044: "OFFICE_PHOTOGRAPHIC_PHOTOCOPY",
    5045: "COMPUTERS_COMPUTER_PERIPHERAL",
    5046: "COMMERCIAL_EQUIPMENT_NOT",
    5047: "MEDICAL_DENTAL_OPHTHALMIC",
    5051: "METAL_SERVICE_CENTERS",
    5065: "ELECTRICAL_PARTS_AND",
    5072: "HARDWARE_EQUIPMENT_AND",
    5074: "PLUMBING_AND_HEATING",
    5085: "INDUSTRIAL_SUPPLIES_NOT",
    5094: "PRECIOUS_STONES_AND",
    5099: "DURABLE_GOODS_NOT",
    5111: "STATIONERY_OFFICE_SUPPLIES",
    5122: "DRUGS_DRUG_PROPRIETORS",
    5131: "PIECE_GOODS_NOTIONS",
    5137: "MENS_WOMENS_AND",
    5139: "COMMERCIAL_FOOTWEAR",
    5169: "CHEMICALS_AND_ALLIED",
    5172: "PETROLEUM_AND_PETROLEUM",
    5192: "BOOKS_PERIODICALS_AND",
    5193: "FLORISTS_SUPPLIES_NURSERY",
    5198: "PAINTS_VARNISHES_AND",
    5199: "NON_DURABLE_GOODS",
    5200: "HOME_SUPPLY_WAREHOUSE",
    5211: "LUMBER_AND_BUILDING",
    5231: "GLASS_PAINT_AND",
    5251: "HARDWARE_STORES",
    5261: "NURSERIES_LAWN",
    5271: "MOBILE_HOME_DEALERS",
    5300: "WHOLESALE_CLUBS",
    5309: "DUTY_FREE_STORE",
    5310: "DISCOUNT_STORES",
    5311: "DEPARTMENT_STORES",
    5331: "VARIETY_STORES",
    5399: "MISC_GENERAL_MERCHANDISE",
    5422: "MEAT_PROVISIONERS",
    5441: "CANDY_NUT_AND",
    5451: "DAIRY_PRODUCTS_STORES",
    5462: "BAKERIES",
    5499: "MISC_FOOD_STORES",
    5511: "CAR_AND_TRUCK",
    5521: "AUTOMOBILE_AND_TRUCK",
    5531: "AUTOMOBILE_SUPPLY_STORES",
    5532: "AUTOMOTIVE_TIRE_STORES",
    5533: "AUTOMOTIVE_PARTS_ACCESSORIES",
    5541: "SERVICE_STATIONS",
    5542: "AUTOMATED_FUEL_DISPENSERS",
    5551: "BOAT_DEALERS",
    5561: "RECREATIONAL_AND_UTILITY",
    5571: "MOTORCYCLE_DEALERS",
    5592: "MOTOR_HOME_DEALERS",
    5598: "SNOWMOBILE_DEALERS",
    5599: "MISCELLANEOUS_AUTO_DEALERS",
    5611: "MENS_AND_BOYS",
    5621: "WOMENS_READY_TO",
    5631: "WOMENS_ACCESSORY_AND",
    5641: "CHILDRENS_AND_INFANTS",
    5651: "FAMILY_CLOTHING_STORES",
    5655: "SPORTS_APPAREL_RIDING",
    5661: "SHOE_STORES",
    5681: "FURRIERS_AND_FUR",
    5691: "MENS_AND_WOMENS",
    5697: "TAILORS_SEAMSTRESS_MENDING",
    5698: "WIG_AND_TOUPEE",
    5699: "MISCELLANEOUS_APPAREL_AND",
    5712: "FURNITURE_HOME_FURNISHINGS",
    5713: "FLOOR_COVERING_STORES",
    5714: "DRAPERY_WINDOW_COVERING",
    5718: "FIREPLACE_FIREPLACE_SCREENS",
    5719: "MISCELLANEOUS_HOME_FURNISHING",
    5722: "HOUSEHOLD_APPLIANCE_STORES",
    5732: "ELECTRONIC_SALES",
    5733: "MUSIC_STORES_MUSICAL",
    5734: "COMPUTER_SOFTWARE_STORES",
    5735: "RECORD_SHOPS",
    5811: "CATERERS",
    5812: "EATING_PLACES_AND",
    5813: "DRINKING_PLACES_ALCOHOLIC",
    5814: "FAST_FOOD_RESTAURANTS",
    5815: "DIGITAL_GOODS_MEDIA",
    5816: "DIGITAL_GOODS_GAMES",
    5817: "DIGITAL_GOODS_APPLICATIONS",
    5818: "DIGITAL_GOODS_LARGE",
    5832: "ANTIQUE_SHOPS",
    5912: "DRUG_STORES_AND",
    5921: "PACKAGE_STORES",
    5931: "USED_MERCHANDISE_AND",
    5932: "ANTIQUE_SHOPS",
    5933: "PAWN_SHOPS_AND",
    5935: "WRECKING_AND_SALVAGE",
    5937: "ANTIQUE_REPRODUCTIONS",
    5940: "BICYCLE_SHOPS",
    5941: "SPORTING_GOODS_STORES",
    5942: "BOOK_STORES",
    5943: "STATIONERY_STORES_OFFICE",
    5944: "WATCH_CLOCK_JEWELRY",
    5945: "HOBBY_TOY_AND",
    5946: "CAMERA_AND_PHOTOGRAPHIC",
    5947: "CARD_SHOPS_GIFT",
    5948: "LEATHER_GOODS_STORES",
    5949: "SEWING_NEEDLE_FABRIC",
    5950: "GLASSWARE_CRYSTAL_STORES",
    5960: "DIRECT_MARKETING",
    5961: "MAIL_ORDER_HOUSES",
    5962: "DIRECT_MARKETING",
    5963: "DOOR_TO_DOOR",
    5964: "DIRECT_MARKETING",
    5965: "DIRECT_MARKETING",
    5966: "DIRECT_MARKETING",
    5967: "DIRECT_MARKETING",
    5968: "DIRECT_MARKETING",
    5969: "DIRECT_MARKETING",
    5970: "ARTISTS_SUPPLY_AND",
    5971: "ART_DEALERS_AND",
    5972: "STAMP_AND_COIN",
    5973: "RELIGIOUS_GOODS_STORES",
    5975: "HEARING_AIDS",
    5976: "ORTHOPEDIC_GOODS_PROSTHETIC",
    5977: "COSMETIC_STORES",
    5978: "TYPEWRITER_STORES",
    5983: "FUEL_FUEL",
    5992: "FLORISTS",
    5993: "CIGAR_STORES_AND",
    5994: "NEWS_DEALERS_AND",
    5995: "PET_SHOPS_PET",
    5996: "SWIMMING_POOLS",
    5997: "ELECTRIC_RAZOR_STORES",
    5998: "TENT_AND_AWNING",
    5999: "MISCELLANEOUS_AND_SPECIALTY",
    6010: "FINANCIAL_INSTITUTIONS",
    6011: "FINANCIAL_INSTITUTIONS",
    6012: "FINANCIAL_INSTITUTIONS",
    6051: "NON_FINANCIAL_INSTITUTIONS",
    6211: "SECURITY_BROKERS_DEALERS",
    6300: "INSURANCE_SALES_UNDERWRITING",
    6381: "INSURANCE_PREMIUMS_NO",
    6399: "INSURANCE_NOT_ELSEWHERE",
    6513: "REAL_ESTATE_AGENTS",
    7011: "LODGING_HOTELS",
    7012: "TIMESHARES",
    7032: "SPORTING_AND_RECREATIONAL",
    7033: "TRAILER_PARKS_AND",
    7210: "LAUNDRY_CLEANING_AND",
    7211: "LAUNDRY_FAMILY",
    7216: "DRY_CLEANERS",
    7217: "CARPET_AND_UPHOLSTERY",
    7221: "PHOTOGRAPHIC_STUDIOS",
    7230: "BARBER_AND_BEAUTY",
    7251: "SHOP_REPAIR_SHOPS",
    7261: "FUNERAL_SERVICE_AND",
    7273: "DATING_AND_ESCORT",
    7276: "TAX_PREPARATION_SERVICE",
    7277: "COUNSELING_SERVICE",
    7278: "BUYING_SHOPPING_SERVICES_CLUBS",
    7296: "CLOTHING_RENTAL",
    7297: "MASSAGE_PARLORS",
    7298: "HEALTH_AND_BEAUTY",
    7299: "MISCELLANEOUS_PERSONAL_SERVICES",
    7311: "ADVERTISING_SERVICES",
    7321: "CONSUMER_CREDIT_REPORTING",
    7332: "BLUEPRINTING_AND_PHOTOCOPYING",
    7333: "COMMERCIAL_PHOTOGRAPHY_ART",
    7338: "QUICK_COPY_REPRODUCTION",
    7339: "STENOGRAPHIC_AND_SECRETARIAL",
    7342: "EXTERMINATING_AND_DISINFECTING",
    7349: "CLEANING_AND_MAINTENANCE",
    7361: "EMPLOYMENT_AGENCIES_TEMPORARY",
    7372: "COMPUTER_PROGRAMMING_INTEGRATED",
    7375: "INFORMATION_RETRIEVAL_SERVICES",
    7379: "COMPUTER_MAINTENANCE_AND",
    7392: "MANAGEMENT_CONSULTING_AND",
    7393: "PROTECTIVE_AND_SECURITY",
    7394: "EQUIPMENT_RENTAL_AND",
    7395: "PHOTOFINISHING_LABORATORIES_PHOTO",
    7399: "BUSINESS_SERVICES_NOT",
    7511: "TRUCK_STOP",
    7512: "CAR_RENTAL_COMPANIES",
    7513: "TRUCK_AND_UTILITY",
    7519: "MOTOR_HOME_AND",
    7523: "AUTOMOBILE_PARKING_LOTS",
    7531: "AUTOMOTIVE_BODY_REPAIR",
    7534: "TIRE_RE_TREADING",
    7535: "PAINT_SHOPS",
    7538: "AUTOMOTIVE_SERVICE_SHOPS",
    7542: "CAR_WASHES",
    7549: "TOWING_SERVICES",
    7622: "RADIO_REPAIR_SHOPS",
    7623: "AIR_CONDITIONING_AND",
    7629: "ELECTRICAL_AND_SMALL",
    7631: "WATCH_CLOCK_AND",
    7641: "FURNITURE_FURNITURE_REPAIR",
    7692: "WELDING_REPAIR",
    7699: "REPAIR_SHOPS_AND",
    7800: "GOVERNMENT_OWNED_LOTTERIES",
    7801: "GOVERNMENT_LICENSED_ON",
    7802: "GOVERNMENT_LICENSED_HORSE_DOG",
    7829: "MOTION_PICTURES_AND",
    7832: "MOTION_PICTURE_THEATERS",
    7841: "VIDEO_TAPE_RENTAL",
    7911: "DANCE_HALLS_STUDIOS",
    7922: "THEATRICAL_PRODUCERS_EXCEPT",
    7929: "BANDS_ORCHESTRAS_AND",
    7932: "BILLIARD_AND_POOL",
    7933: "BOWLING_ALLEYS",
    7941: "COMMERCIAL_SPORTS_ATHLETIC",
    7991: "TOURIST_ATTRACTIONS_AND",
    7992: "GOLF_COURSES",
    7993: "VIDEO_AMUSEMENT_GAME",
    7994: "VIDEO_GAME_ARCADES_ESTABLISHMENTS",
    7995: "BETTING_INCLUDING_LOTTERY",
    7996: "AMUSEMENT_PARKS_CARNIVALS",
    7997: "MEMBERSHIP_CLUBS_SPORTS",
    7998: "AQUARIUMS_SEA_AQUARIUMS",
    7999: "RECREATION_SERVICES_NOT",
    8011: "DOCTORS_AND_PHYSICIANS",
    8021: "DENTISTS_AND_ORTHODONTISTS",
    8031: "OSTEOPATHS",
    8041: "CHIROPRACTORS",
    8042: "OPTOMETRISTS_AND_OPHTHALMOLOGISTS",
    8043: "OPTICIANS_OPTICIANS_GOODS",
    8044: "OPTICIANS_OPTICAL_GOODS",
    8049: "PODIATRISTS_AND_CHIROPODISTS",
    8050: "NURSING_AND_PERSONAL",
    8062: "HOSPITALS",
    8071: "MEDICAL_AND_DENTAL",
    8099: "MEDICAL_SERVICES_AND",
    8111: "LEGAL_SERVICES_AND",
    8211: "ELEMENTARY_AND_SECONDARY",
    8220: "COLLEGES_JUNIOR_COLLEGES",
    8241: "CORRESPONDENCE_SCHOOLS",
    8244: "BUSINESS_AND_SECRETARIAL",
    8249: "VOCATIONAL_SCHOOLS_AND",
    8299: "SCHOOLS_AND_EDUCATIONAL",
    8351: "CHILD_CARE_SERVICES",
    8398: "CHARITABLE_AND_SOCIAL",
    8641: "CIVIC_FRATERNAL_AND",
    8651: "POLITICAL_ORGANIZATIONS",
    8661: "RELIGIOUS_ORGANIZATIONS",
    8675: "AUTOMOBILE_ASSOCIATIONS",
    8699: "MEMBERSHIP_ORGANIZATIONS",
    8734: "TESTING_LABORATORIES",
    8911: "ARCHITECTURAL_ENGINEERING",
    8931: "ACCOUNTING_AUDITING_AND",
    8999: "PROFESSIONAL_SERVICES",
    9211: "COURT_COSTS_INCLUDING",
    9222: "FINES",
    9223: "BAIL_AND_BOND",
    9311: "TAX_PAYMENTS",
    9399: "GOVERNMENT_SERVICES",
    9402: "POSTAL_SERVICES",
    9405: "INTRA_GOVERNMENT",
    9700: "AUTOMATED_REFERRAL_SERVICE",
    9701: "VISA_CREDENTIAL_SERVICE",
    9702: "GCAS_EMERGENCY_SERVICES",
    9950: "INTRA_COMPANY",
}
MCCTransactionCategoryT = TypeVar("MCCTransactionCategoryT", bound=MCCCodeCategory)


# class MCCCategories(str, enum.Enum):
#     VETERINARY_SERVICES = "VETERINARY_SERVICES"
#     AGRICULTURAL_CO_OPERATIVES = "AGRICULTURAL_CO_OPERATIVES"
#     HORTICULTURAL_SERVICES_LANDSCAPING = "HORTICULTURAL_SERVICES_LANDSCAPING"
#     GENERAL_CONTRACTORS_RESIDENTIAL = "GENERAL_CONTRACTORS_RESIDENTIAL"
#     AIR_CONDITIONING_CONTRACTORS = "AIR_CONDITIONING_CONTRACTORS"
#     ELECTRICAL_CONTRACTORS = "ELECTRICAL_CONTRACTORS"
#     INSULATION_CONTRACTORS = "INSULATION_CONTRACTORS"
#     CARPENTRY_CONTRACTORS = "CARPENTRY_CONTRACTORS"
#     ROOFING_CONTRACTORS = "ROOFING_CONTRACTORS"
#     CONTRACTORS_CONCRETE = "CONTRACTORS_CONCRETE"
#     CONTRACTORS_SPECIAL = "CONTRACTORS_SPECIAL"
#     MISCELLANEOUS_PUBLISHING_AND = "MISCELLANEOUS_PUBLISHING_AND"
#     TYPESETTING_PLATE_MAKING = "TYPESETTING_PLATE_MAKING"
#     SPECIALTY_CLEANING_POLISHING = "SPECIALTY_CLEANING_POLISHING"
#     UNITED_AIRLINES = "UNITED_AIRLINES"
#     AMERICAN_AIRLINES = "AMERICAN_AIRLINES"
#     PAN_AMERICAN = "PAN_AMERICAN"
#     TRANS_WORLD_AIRLINES = "TRANS_WORLD_AIRLINES"
#     BRITISH_AIRWAYS = "BRITISH_AIRWAYS"
#     JAPAN_AIRLINES = "JAPAN_AIRLINES"
#     AIR_FRANCE = "AIR_FRANCE"
#     LUFTHANSA = "LUFTHANSA"
#     AIR_CANADA = "AIR_CANADA"
#     KLM_ROYAL_DUTCH = "KLM_ROYAL_DUTCH"
#     AEORFLOT = "AEORFLOT"
#     QANTAS = "QANTAS"
#     ALITALIA = "ALITALIA"
#     SAUDIA_ARABIAN_AIRLINES = "SAUDIA_ARABIAN_AIRLINES"
#     SWISSAIR = "SWISSAIR"
#     SAS = "SAS"
#     SOUTH_AFRICAN_AIRWAYS = "SOUTH_AFRICAN_AIRWAYS"
#     VARIG_BRAZIL = "VARIG_BRAZIL"
#     AIR_INDIA = "AIR_INDIA"
#     AIR_ALGERIE = "AIR_ALGERIE"
#     PHILIPPINE_AIRLINES = "PHILIPPINE_AIRLINES"
#     MEXICANA = "MEXICANA"
#     PAKISTAN_INTERNATIONAL = "PAKISTAN_INTERNATIONAL"
#     AIR_NEW_ZEALAND = "AIR_NEW_ZEALAND"
#     UTA_INTERAIR = "UTA_INTERAIR"
#     AIR_MALTA = "AIR_MALTA"
#     SABENA = "SABENA"
#     AEROLINEAS_ARGENTINAS = "AEROLINEAS_ARGENTINAS"
#     OLYMPIC_AIRWAYS = "OLYMPIC_AIRWAYS"
#     EL_AL = "EL_AL"
#     ANSETT_AIRLINES = "ANSETT_AIRLINES"
#     AUSTRAINLIAN_AIRLINES = "AUSTRAINLIAN_AIRLINES"
#     TAP_PORTUGAL = "TAP_PORTUGAL"
#     VASP_BRAZIL = "VASP_BRAZIL"
#     EGYPTAIR = "EGYPTAIR"
#     KUWAIT_AIRLINES = "KUWAIT_AIRLINES"
#     AVIANCA = "AVIANCA"
#     GULF_AIR_BAHRAIN = "GULF_AIR_BAHRAIN"
#     BALKAN_BULGARIAN_AIRLINES = "BALKAN_BULGARIAN_AIRLINES"
#     FINNAIR = "FINNAIR"
#     AER_LINGUS = "AER_LINGUS"
#     AIR_LANKA = "AIR_LANKA"
#     NIGERIA_AIRWAYS = "NIGERIA_AIRWAYS"
#     CRUZEIRO_DO_SUL = "CRUZEIRO_DO_SUL"
#     THY_TURKEY = "THY_TURKEY"
#     ROYAL_AIR_MAROC = "ROYAL_AIR_MAROC"
#     TUNIS_AIR = "TUNIS_AIR"
#     ICELANDAIR = "ICELANDAIR"
#     AUSTRIAN_AIRLINES = "AUSTRIAN_AIRLINES"
#     LANCHILE = "LANCHILE"
#     AVIACO_SPAIN = "AVIACO_SPAIN"
#     LADECO_CHILE = "LADECO_CHILE"
#     LAB_BOLIVIA = "LAB_BOLIVIA"
#     QUEBECAIRE = "QUEBECAIRE"
#     EASTWEST_AIRLINES_AUSTRALIA = "EASTWEST_AIRLINES_AUSTRALIA"
#     DELTA = "DELTA"
#     NORTHWEST = "NORTHWEST"
#     CONTINENTAL = "CONTINENTAL"
#     AIRLINES = "AIRLINES"
#     WESTERN = "WESTERN"
#     US_AIR = "US_AIR"
#     AIRINTER = "AIRINTER"
#     SOUTHWEST = "SOUTHWEST"
#     SUN_COUNTRY_AIRLINES = "SUN_COUNTRY_AIRLINES"
#     AIR_BRITISH_COLUBIA = "AIR_BRITISH_COLUBIA"
#     SINGAPORE_AIRLINES = "SINGAPORE_AIRLINES"
#     AEROMEXICO = "AEROMEXICO"
#     THAI_AIRWAYS = "THAI_AIRWAYS"
#     CHINA_AIRLINES = "CHINA_AIRLINES"
#     NORDAIR = "NORDAIR"
#     KOREAN_AIRLINES = "KOREAN_AIRLINES"
#     AIR_AFRIGUE = "AIR_AFRIGUE"
#     EVA_AIRLINES = "EVA_AIRLINES"
#     MIDWEST_EXPRESS_AIRLINES = "MIDWEST_EXPRESS_AIRLINES"
#     METRO_AIRLINES = "METRO_AIRLINES"
#     CROATIA_AIRLINES = "CROATIA_AIRLINES"
#     TRANSAERO = "TRANSAERO"
#     ZAMBIA_AIRWAYS = "ZAMBIA_AIRWAYS"
#     AIR_ZIMBABWE = "AIR_ZIMBABWE"
#     CATHAY_PACIFIC = "CATHAY_PACIFIC"
#     MALAYSIAN_AIRLINE_SYSTEM = "MALAYSIAN_AIRLINE_SYSTEM"
#     IBERIA = "IBERIA"
#     GARUDA_INDONESIA = "GARUDA_INDONESIA"
#     BRAATHENS_SAFE_NORWAY = "BRAATHENS_SAFE_NORWAY"
#     WINGS_AIRWAYS = "WINGS_AIRWAYS"
#     BRITISH_MIDLAND = "BRITISH_MIDLAND"
#     WINDWARD_ISLAND = "WINDWARD_ISLAND"
#     VIASA = "VIASA"
#     VALLEY_AIRLINES = "VALLEY_AIRLINES"
#     TAN = "TAN"
#     TALAIR = "TALAIR"
#     TACA_INTERNATIONAL = "TACA_INTERNATIONAL"
#     SURINAM_AIRWAYS = "SURINAM_AIRWAYS"
#     SUN_WORLD_INTERNATIONAL = "SUN_WORLD_INTERNATIONAL"
#     SUNBELT_AIRLINES = "SUNBELT_AIRLINES"
#     SUDAN_AIRWAYS = "SUDAN_AIRWAYS"
#     SINGLETON = "SINGLETON"
#     SIMMONS_AIRLINES = "SIMMONS_AIRLINES"
#     SCENIC_AIRLINES = "SCENIC_AIRLINES"
#     VIRGIN_ATLANTIC = "VIRGIN_ATLANTIC"
#     SAN_JUAN_AIRLINES = "SAN_JUAN_AIRLINES"
#     LUXAIR = "LUXAIR"
#     AIR_ZAIRE = "AIR_ZAIRE"
#     PRINCEVILLE = "PRINCEVILLE"
#     PBA = "PBA"
#     ALL_NIPPON_AIRWAYS = "ALL_NIPPON_AIRWAYS"
#     NORONTAIR = "NORONTAIR"
#     NEW_YORK_HELICOPTER = "NEW_YORK_HELICOPTER"
#     NOUNT_COOK = "NOUNT_COOK"
#     CANADIAN_AIRLINES_INTERNATIONAL = "CANADIAN_AIRLINES_INTERNATIONAL"
#     NATIONAIR = "NATIONAIR"
#     METROFLIGHT_AIRLINES = "METROFLIGHT_AIRLINES"
#     MESA_AIR = "MESA_AIR"
#     MALEV = "MALEV"
#     LOT_POLAND = "LOT_POLAND"
#     LIAT = "LIAT"
#     LAV_VENEZUELA = "LAV_VENEZUELA"
#     LAP_PARAGUAY = "LAP_PARAGUAY"
#     LACSA_COSTA_RICA = "LACSA_COSTA_RICA"
#     JUGOSLAV_AIR = "JUGOSLAV_AIR"
#     ISLAND_AIRLINES = "ISLAND_AIRLINES"
#     IRAN_AIR = "IRAN_AIR"
#     INDIAN_AIRLINES = "INDIAN_AIRLINES"
#     HAWAIIAN_AIR = "HAWAIIAN_AIR"
#     HAVASU_AIRLINES = "HAVASU_AIRLINES"
#     FUYANA_AIRWAYS = "FUYANA_AIRWAYS"
#     GOLDEN_PACIFIC_AIR = "GOLDEN_PACIFIC_AIR"
#     FREEDOM_AIR = "FREEDOM_AIR"
#     DOMINICANA = "DOMINICANA"
#     DAN_AIR_SERVICES = "DAN_AIR_SERVICES"
#     CUMBERLAND_AIRLINES = "CUMBERLAND_AIRLINES"
#     CSA = "CSA"
#     CROWN_AIR = "CROWN_AIR"
#     COPA = "COPA"
#     COMPANIA_FAUCETT = "COMPANIA_FAUCETT"
#     TRANSPORTES_AEROS_MILITARES = "TRANSPORTES_AEROS_MILITARES"
#     COMMAND_AIRWAYS = "COMMAND_AIRWAYS"
#     COMAIR = "COMAIR"
#     CAYMAN_AIRWAYS = "CAYMAN_AIRWAYS"
#     SAETA_SOCIAEDAD_ECUATORIANOS = "SAETA_SOCIAEDAD_ECUATORIANOS"
#     SASHA_SERVICIO_AERO = "SASHA_SERVICIO_AERO"
#     CAPITOL_AIR = "CAPITOL_AIR"
#     BWIA = "BWIA"
#     BROKWAY_AIR = "BROKWAY_AIR"
#     BEMIDJI_AIRLINES = "BEMIDJI_AIRLINES"
#     BAR_HARBOR_AIRLINES = "BAR_HARBOR_AIRLINES"
#     BAHAMASAIR = "BAHAMASAIR"
#     AVIATECA_GUATEMALA = "AVIATECA_GUATEMALA"
#     AVENSA = "AVENSA"
#     AUSTRIAN_AIR_SERVICE = "AUSTRIAN_AIR_SERVICE"
#     ALOHA_AIRLINES = "ALOHA_AIRLINES"
#     ALM = "ALM"
#     AMERICA_WEST = "AMERICA_WEST"
#     TRUMP_AIRLINE = "TRUMP_AIRLINE"
#     ALASKA_AIRLINES = "ALASKA_AIRLINES"
#     AMERICAN_TRANS_AIR = "AMERICAN_TRANS_AIR"
#     AIR_CHINA = "AIR_CHINA"
#     RENO_AIR_INC = "RENO_AIR_INC"
#     AIR_SEYCHELLES = "AIR_SEYCHELLES"
#     AIR_PANAMA = "AIR_PANAMA"
#     AIR_JAMAICA = "AIR_JAMAICA"
#     AIR_DJIBOUTI = "AIR_DJIBOUTI"
#     AERO_VIRGIN_ISLANDS = "AERO_VIRGIN_ISLANDS"
#     AERO_PERU = "AERO_PERU"
#     AEROLINEAS_NICARAGUENSIS = "AEROLINEAS_NICARAGUENSIS"
#     AERO_COACH_AVAIATION = "AERO_COACH_AVAIATION"
#     ARIANA_AFGHAN = "ARIANA_AFGHAN"
#     CYPRUS_AIRWAYS = "CYPRUS_AIRWAYS"
#     ECUATORIANA = "ECUATORIANA"
#     ETHIOPIAN_AIRLINES = "ETHIOPIAN_AIRLINES"
#     KENYA_AIRLINES = "KENYA_AIRLINES"
#     AIR_MAURITIUS = "AIR_MAURITIUS"
#     WIDEROS_FLYVESELSKAP = "WIDEROS_FLYVESELSKAP"
#     AFFILIATED_AUTO_RENTAL = "AFFILIATED_AUTO_RENTAL"
#     AMERICAN_INTL_RENT = "AMERICAN_INTL_RENT"
#     BROOKS_RENT_A = "BROOKS_RENT_A"
#     ACTION_AUTO_RENTAL = "ACTION_AUTO_RENTAL"
#     CAR_RENTAL = "CAR_RENTAL"
#     HERTZ_RENT_A = "HERTZ_RENT_A"
#     PAYLESS_CAR_RENTAL = "PAYLESS_CAR_RENTAL"
#     SNAPPY_CAR_RENTAL = "SNAPPY_CAR_RENTAL"
#     AIRWAYS_RENT_A = "AIRWAYS_RENT_A"
#     ALTRA_AUTO_RENTAL = "ALTRA_AUTO_RENTAL"
#     AGENCY_RENT_A = "AGENCY_RENT_A"
#     BUDGET_RENT_A = "BUDGET_RENT_A"
#     HOLIDAY_RENT_A = "HOLIDAY_RENT_A"
#     RENT_A_WRECK = "RENT_A_WRECK"
#     AJAX_RENT_A = "AJAX_RENT_A"
#     EUROP_CAR = "EUROP_CAR"
#     TROPICAL_RENT_A = "TROPICAL_RENT_A"
#     SHOWCASE_RENTAL_CARS = "SHOWCASE_RENTAL_CARS"
#     ALAMO_RENT_A = "ALAMO_RENT_A"
#     AVIS_RENT_A = "AVIS_RENT_A"
#     DOLLAR_RENT_A = "DOLLAR_RENT_A"
#     EUROPE_BY_CAR = "EUROPE_BY_CAR"
#     NATIONAL_CAR_RENTAL = "NATIONAL_CAR_RENTAL"
#     KEMWELL_GROUP_RENT = "KEMWELL_GROUP_RENT"
#     THRIFTY_RENT_A = "THRIFTY_RENT_A"
#     TILDEN_TENT_A = "TILDEN_TENT_A"
#     ECONO_CAR_RENT = "ECONO_CAR_RENT"
#     AUTO_HOST_COST = "AUTO_HOST_COST"
#     ENTERPRISE_RENT_A = "ENTERPRISE_RENT_A"
#     GENERAL_RENT_A = "GENERAL_RENT_A"
#     A_1_RENT = "A_1_RENT"
#     GODFREY_NATL_RENT = "GODFREY_NATL_RENT"
#     ALPHA_RENT_A = "ALPHA_RENT_A"
#     ANSA_INTL_RENT = "ANSA_INTL_RENT"
#     ALLSTAE_RENT_A = "ALLSTAE_RENT_A"
#     AVCAR_RENT_A = "AVCAR_RENT_A"
#     AUTOMATE_RENT_A = "AUTOMATE_RENT_A"
#     AVON_RENT_A = "AVON_RENT_A"
#     CAREY_RENT_A = "CAREY_RENT_A"
#     INSURANCE_RENT_A = "INSURANCE_RENT_A"
#     MAJOR_RENT_A = "MAJOR_RENT_A"
#     REPLACEMENT_RENT_A = "REPLACEMENT_RENT_A"
#     RESERVE_RENT_A = "RESERVE_RENT_A"
#     UGLY_DUCKLING_RENT = "UGLY_DUCKLING_RENT"
#     USA_RENT_A = "USA_RENT_A"
#     VALUE_RENT_A = "VALUE_RENT_A"
#     AUTOHANSA_RENT_A = "AUTOHANSA_RENT_A"
#     CITE_RENT_A = "CITE_RENT_A"
#     INTERENT_RENT_A = "INTERENT_RENT_A"
#     MILLEVILLE_RENT_A = "MILLEVILLE_RENT_A"
#     VIA_ROUTE_RENT = "VIA_ROUTE_RENT"
#     HOLIDAY_INNS_HOLIDAY = "HOLIDAY_INNS_HOLIDAY"
#     BEST_WESTERN_HOTELS = "BEST_WESTERN_HOTELS"
#     SHERATON_HOTELS = "SHERATON_HOTELS"
#     HILTON_HOTELS = "HILTON_HOTELS"
#     FORTE_HOTELS = "FORTE_HOTELS"
#     GOLDEN_TULIP_HOTELS = "GOLDEN_TULIP_HOTELS"
#     FRIENDSHIP_INNS = "FRIENDSHIP_INNS"
#     QUALITY_INNS_QUALITY = "QUALITY_INNS_QUALITY"
#     MARRIOTT_HOTELS = "MARRIOTT_HOTELS"
#     DAYS_INN_DAYSTOP = "DAYS_INN_DAYSTOP"
#     ARABELLA_HOTELS = "ARABELLA_HOTELS"
#     INTER_CONTINENTAL_HOTELS = "INTER_CONTINENTAL_HOTELS"
#     WESTIN_HOTELS = "WESTIN_HOTELS"
#     RODEWAY_INNS = "RODEWAY_INNS"
#     LA_QUINTA_MOTOR = "LA_QUINTA_MOTOR"
#     AMERICANA_HOTELS = "AMERICANA_HOTELS"
#     SOL_HOTELS = "SOL_HOTELS"
#     PULLMAN_INTERNATIONAL_HOTELS = "PULLMAN_INTERNATIONAL_HOTELS"
#     MERIDIEN_HOTELS = "MERIDIEN_HOTELS"
#     CREST_HOTELS_SEE = "CREST_HOTELS_SEE"
#     TOKYO_HOTEL = "TOKYO_HOTEL"
#     PENNSULA_HOTEL = "PENNSULA_HOTEL"
#     WELCOMGROUP_HOTELS = "WELCOMGROUP_HOTELS"
#     DUNFEY_HOTELS = "DUNFEY_HOTELS"
#     DOWNTOWNER_PASSPORT_HOTEL = "DOWNTOWNER_PASSPORT_HOTEL"
#     RED_LION_HOTELS = "RED_LION_HOTELS"
#     CP_HOTELS = "CP_HOTELS"
#     RENAISSANCE_HOTELS_STOUFFER = "RENAISSANCE_HOTELS_STOUFFER"
#     ASTIR_HOTELS = "ASTIR_HOTELS"
#     SUN_ROUTE_HOTELS = "SUN_ROUTE_HOTELS"
#     HOTEL_IBIS = "HOTEL_IBIS"
#     SOUTHERN_PACIFIC_HOTELS = "SOUTHERN_PACIFIC_HOTELS"
#     HILTON_INTERNATIONAL = "HILTON_INTERNATIONAL"
#     AMFAC_HOTELS = "AMFAC_HOTELS"
#     ANA_HOTEL = "ANA_HOTEL"
#     CONCORDE_HOTELS = "CONCORDE_HOTELS"
#     IBEROTEL_HOTELS = "IBEROTEL_HOTELS"
#     HOTEL_OKURA = "HOTEL_OKURA"
#     ROYAL_HOTELS = "ROYAL_HOTELS"
#     FOUR_SEASONS_HOTELS = "FOUR_SEASONS_HOTELS"
#     CIGA_HOTELS = "CIGA_HOTELS"
#     SHANGRI_LA_INTERNATIONAL = "SHANGRI_LA_INTERNATIONAL"
#     HOTELES_MELIA = "HOTELES_MELIA"
#     AUBERGE_DES_GOVERNEURS = "AUBERGE_DES_GOVERNEURS"
#     REGAL_8_INNS = "REGAL_8_INNS"
#     COAST_HOTELS = "COAST_HOTELS"
#     PARK_INNS_INTERNATIONAL = "PARK_INNS_INTERNATIONAL"
#     JOLLY_HOTELS = "JOLLY_HOTELS"
#     HOTELS_MOTELS_INNS_RESORTS = "HOTELS_MOTELS_INNS_RESORTS"
#     COMFORT_INNS = "COMFORT_INNS"
#     JOURNEYS_END_MOTLS = "JOURNEYS_END_MOTLS"
#     RELAX_INNS = "RELAX_INNS"
#     LADBROKE_HOTELS = "LADBROKE_HOTELS"
#     FORUM_HOTELS = "FORUM_HOTELS"
#     MIYAKO_HOTELS = "MIYAKO_HOTELS"
#     SANDMAN_HOTELS = "SANDMAN_HOTELS"
#     VENTURE_INNS = "VENTURE_INNS"
#     VAGABOND_HOTELS = "VAGABOND_HOTELS"
#     MANDARIN_ORIENTAL_HOTEL = "MANDARIN_ORIENTAL_HOTEL"
#     HOTEL_MERCURE = "HOTEL_MERCURE"
#     DELTA_HOTEL = "DELTA_HOTEL"
#     SAS_HOTELS = "SAS_HOTELS"
#     PRINCESS_HOTELS_INTERNATIONAL = "PRINCESS_HOTELS_INTERNATIONAL"
#     HUNGAR_HOTELS = "HUNGAR_HOTELS"
#     SOKOS_HOTELS = "SOKOS_HOTELS"
#     DORAL_HOTELS = "DORAL_HOTELS"
#     HELMSLEY_HOTELS = "HELMSLEY_HOTELS"
#     FAIRMONT_HOTELS = "FAIRMONT_HOTELS"
#     SONESTA_HOTELS = "SONESTA_HOTELS"
#     OMNI_HOTELS = "OMNI_HOTELS"
#     CUNARD_HOTELS = "CUNARD_HOTELS"
#     HOSPITALITY_INTERNATIONAL = "HOSPITALITY_INTERNATIONAL"
#     REGENT_INTERNATIONAL_HOTELS = "REGENT_INTERNATIONAL_HOTELS"
#     PANNONIA_HOTELS = "PANNONIA_HOTELS"
#     NOAHS_HOTELS = "NOAHS_HOTELS"
#     MOVENPICK_HOTELS = "MOVENPICK_HOTELS"
#     TRAVELODGE = "TRAVELODGE"
#     TELFORD_INTERNATIONAL = "TELFORD_INTERNATIONAL"
#     MERLIN_HOTELS = "MERLIN_HOTELS"
#     DORINT_HOTELS = "DORINT_HOTELS"
#     HOTLE_UNIVERSALE = "HOTLE_UNIVERSALE"
#     PRINCE_HOTELS = "PRINCE_HOTELS"
#     DAN_HOTELS = "DAN_HOTELS"
#     RANK_HOTELS = "RANK_HOTELS"
#     SWISSOTEL = "SWISSOTEL"
#     RESO_HOTELS = "RESO_HOTELS"
#     SAROVA_HOTELS = "SAROVA_HOTELS"
#     RAMADA_INNS_RAMADA = "RAMADA_INNS_RAMADA"
#     HO_JO_INN = "HO_JO_INN"
#     MOUNT_CHARLOTTE_THISTLE = "MOUNT_CHARLOTTE_THISTLE"
#     HYATT_HOTEL = "HYATT_HOTEL"
#     SOFITEL_HOTELS = "SOFITEL_HOTELS"
#     NOVOTEL_HOTELS = "NOVOTEL_HOTELS"
#     STEIGENBERGER_HOTELS = "STEIGENBERGER_HOTELS"
#     ECONO_LODGES = "ECONO_LODGES"
#     QUEENS_MOAT_HOUSES = "QUEENS_MOAT_HOUSES"
#     SWALLOW_HOTELS = "SWALLOW_HOTELS"
#     HUSA_HOTELS = "HUSA_HOTELS"
#     DE_VERE_HOTELS = "DE_VERE_HOTELS"
#     RADISSON_HOTELS = "RADISSON_HOTELS"
#     RED_ROOK_INNS = "RED_ROOK_INNS"
#     IMPERIAL_LONDON_HOTEL = "IMPERIAL_LONDON_HOTEL"
#     EMBASSY_HOTELS = "EMBASSY_HOTELS"
#     PENTA_HOTELS = "PENTA_HOTELS"
#     LOEWS_HOTELS = "LOEWS_HOTELS"
#     SCANDIC_HOTELS = "SCANDIC_HOTELS"
#     SARA_HOTELS = "SARA_HOTELS"
#     OBEROI_HOTELS = "OBEROI_HOTELS"
#     OTANI_HOTELS = "OTANI_HOTELS"
#     TAJ_HOTELS_INTERNATIONAL = "TAJ_HOTELS_INTERNATIONAL"
#     KNIGHTS_INNS = "KNIGHTS_INNS"
#     METROPOLE_HOTELS = "METROPOLE_HOTELS"
#     HOTELES_EL_PRESIDENTS = "HOTELES_EL_PRESIDENTS"
#     FLAG_INN = "FLAG_INN"
#     HAMPTON_INNS = "HAMPTON_INNS"
#     STAKIS_HOTELS = "STAKIS_HOTELS"
#     MARITIM_HOTELS = "MARITIM_HOTELS"
#     ARCARD_HOTELS = "ARCARD_HOTELS"
#     ARCTIA_HOTELS = "ARCTIA_HOTELS"
#     CAMPANIEL_HOTELS = "CAMPANIEL_HOTELS"
#     IBUSZ_HOTELS = "IBUSZ_HOTELS"
#     RANTASIPI_HOTELS = "RANTASIPI_HOTELS"
#     INTERHOTEL_CEDOK = "INTERHOTEL_CEDOK"
#     CLIMAT_DE_FRANCE = "CLIMAT_DE_FRANCE"
#     CUMULUS_HOTELS = "CUMULUS_HOTELS"
#     DANUBIUS_HOTEL = "DANUBIUS_HOTEL"
#     ADAMS_MARK_HOTELS = "ADAMS_MARK_HOTELS"
#     ALLSTAR_INNS = "ALLSTAR_INNS"
#     BUDGET_HOST_INNS = "BUDGET_HOST_INNS"
#     BUDGETEL_HOTELS = "BUDGETEL_HOTELS"
#     SUISSE_CHALETS = "SUISSE_CHALETS"
#     CLARION_HOTELS = "CLARION_HOTELS"
#     COMPRI_HOTELS = "COMPRI_HOTELS"
#     CONSORT_HOTELS = "CONSORT_HOTELS"
#     COURTYARD_BY_MARRIOTT = "COURTYARD_BY_MARRIOTT"
#     DILLION_INNS = "DILLION_INNS"
#     DOUBLETREE_HOTELS = "DOUBLETREE_HOTELS"
#     DRURY_INNS = "DRURY_INNS"
#     ECONOMY_INNS_OF = "ECONOMY_INNS_OF"
#     EMBASSY_SUITES = "EMBASSY_SUITES"
#     EXEL_INNS = "EXEL_INNS"
#     FARFIELD_HOTELS = "FARFIELD_HOTELS"
#     HARLEY_HOTELS = "HARLEY_HOTELS"
#     MIDWAY_MOTOR_LODGE = "MIDWAY_MOTOR_LODGE"
#     MOTEL_6 = "MOTEL_6"
#     GUEST_QUARTERS_FORMALLY = "GUEST_QUARTERS_FORMALLY"
#     THE_REGISTRY_HOTELS = "THE_REGISTRY_HOTELS"
#     RESIDENCE_INNS = "RESIDENCE_INNS"
#     ROYCE_HOTELS = "ROYCE_HOTELS"
#     SANDMAN_INNS = "SANDMAN_INNS"
#     SHILO_INNS = "SHILO_INNS"
#     SHONEYS_INNS = "SHONEYS_INNS"
#     SUPER8_MOTELS = "SUPER8_MOTELS"
#     THE_RITZ_CARLTON = "THE_RITZ_CARLTON"
#     FLAG_INNS_AUSRALIA = "FLAG_INNS_AUSRALIA"
#     GOLDEN_CHAIN_HOTEL = "GOLDEN_CHAIN_HOTEL"
#     QUALITY_PACIFIC_HOTEL = "QUALITY_PACIFIC_HOTEL"
#     FOUR_SEASONS_HOTEL = "FOUR_SEASONS_HOTEL"
#     FARIFIELD_INN = "FARIFIELD_INN"
#     CARLTON_HOTELS = "CARLTON_HOTELS"
#     CITY_LODGE_HOTELS = "CITY_LODGE_HOTELS"
#     KAROS_HOTELS = "KAROS_HOTELS"
#     PROTEA_HOTELS = "PROTEA_HOTELS"
#     SOUTHERN_SUN_HOTELS = "SOUTHERN_SUN_HOTELS"
#     HILTON_CONRAD = "HILTON_CONRAD"
#     WYNDHAM_HOTEL_AND = "WYNDHAM_HOTEL_AND"
#     RICA_HOTELS = "RICA_HOTELS"
#     INER_NOR_HOTELS = "INER_NOR_HOTELS"
#     SEAINES_PLANATION = "SEAINES_PLANATION"
#     RIO_SUITES = "RIO_SUITES"
#     BROADMOOR_HOTEL = "BROADMOOR_HOTEL"
#     BALLYS_HOTEL_AND = "BALLYS_HOTEL_AND"
#     JOHN_ASCUAGAS_NUGGET = "JOHN_ASCUAGAS_NUGGET"
#     MGM_GRAND_HOTEL = "MGM_GRAND_HOTEL"
#     HARRAHS_HOTELS_AND = "HARRAHS_HOTELS_AND"
#     OPRYLAND_HOTEL = "OPRYLAND_HOTEL"
#     BOCA_RATON_RESORT = "BOCA_RATON_RESORT"
#     HARVEY_BRISTOL_HOTELS = "HARVEY_BRISTOL_HOTELS"
#     COLORADO_BELLE_EDGEWATER_RESORT = "COLORADO_BELLE_EDGEWATER_RESORT"
#     RIVIERA_HOTEL_AND = "RIVIERA_HOTEL_AND"
#     TROPICANA_RESORT_AND = "TROPICANA_RESORT_AND"
#     WOODSIDE_HOTELS_AND = "WOODSIDE_HOTELS_AND"
#     TOWNPLACE_SUITES = "TOWNPLACE_SUITES"
#     MILLENIUM_BROADWAY_HOTEL = "MILLENIUM_BROADWAY_HOTEL"
#     CLUB_MED = "CLUB_MED"
#     BILTMORE_HOTEL_AND = "BILTMORE_HOTEL_AND"
#     CAREFREE_RESORTS = "CAREFREE_RESORTS"
#     ST_REGIS_HOTEL = "ST_REGIS_HOTEL"
#     THE_ELIOT_HOTEL = "THE_ELIOT_HOTEL"
#     CLUBCORP_CLUB_RESORTS = "CLUBCORP_CLUB_RESORTS"
#     WELESLEY_INNS = "WELESLEY_INNS"
#     THE_BEVERLY_HILLS = "THE_BEVERLY_HILLS"
#     CROWNE_PLAZA_HOTELS = "CROWNE_PLAZA_HOTELS"
#     HOMEWOOD_SUITES = "HOMEWOOD_SUITES"
#     PEABODY_HOTELS = "PEABODY_HOTELS"
#     GREENBRIAH_RESORTS = "GREENBRIAH_RESORTS"
#     AMELIA_ISLAND_PLANATION = "AMELIA_ISLAND_PLANATION"
#     THE_HOMESTEAD = "THE_HOMESTEAD"
#     SOUTH_SEAS_RESORTS = "SOUTH_SEAS_RESORTS"
#     HOME2SUITES = "HOME2SUITES"
#     MASTERS_ECONOMY_INNS = "MASTERS_ECONOMY_INNS"
#     RAILROADS = "RAILROADS"
#     LOCAL_SUBURBAN_COMMUTER_PASSENGER = "LOCAL_SUBURBAN_COMMUTER_PASSENGER"
#     PASSENGER_RAILWAYS = "PASSENGER_RAILWAYS"
#     AMBULANCE_SERVICES = "AMBULANCE_SERVICES"
#     TAXICABS_AND_LIMOUSINES = "TAXICABS_AND_LIMOUSINES"
#     BUS_LINES_INCLUDING = "BUS_LINES_INCLUDING"
#     MOTOR_FREIGHT_CARRIERS = "MOTOR_FREIGHT_CARRIERS"
#     COURIER_SERVICES = "COURIER_SERVICES"
#     PUBLIC_WAREHOUSING_STORAGE = "PUBLIC_WAREHOUSING_STORAGE"
#     CRUISE_AND_STEAMSHIP = "CRUISE_AND_STEAMSHIP"
#     BOAT_RENTALS_AND = "BOAT_RENTALS_AND"
#     MARINAS_MARINE_SERVICE = "MARINAS_MARINE_SERVICE"
#     AIRLINES_AIR_CARRIERS = "AIRLINES_AIR_CARRIERS"
#     AIRPORTS_AIRPORT_TERMINALS = "AIRPORTS_AIRPORT_TERMINALS"
#     TRAVEL_AGENCIES_AND = "TRAVEL_AGENCIES_AND"
#     PACKAGE_TOUR_OPERATORS = "PACKAGE_TOUR_OPERATORS"
#     TOLL_AND_BRIDGE = "TOLL_AND_BRIDGE"
#     TRANSPORTATION_SERVICES_NOT = "TRANSPORTATION_SERVICES_NOT"
#     TELECOMMUNICATIONS_EQUIPMENT_INCLUDING = "TELECOMMUNICATIONS_EQUIPMENT_INCLUDING"
#     FAX_SERVICES_TELECOMMUNICATION = "FAX_SERVICES_TELECOMMUNICATION"
#     VISAPHONE = "VISAPHONE"
#     COMPUTER_NETWORK_SERVICES = "COMPUTER_NETWORK_SERVICES"
#     TELEGRAPH_SERVICES = "TELEGRAPH_SERVICES"
#     MONEY_ORDERS = "MONEY_ORDERS"
#     CABLE_AND_OTHER = "CABLE_AND_OTHER"
#     ELECTRIC_GAS_SANITARY = "ELECTRIC_GAS_SANITARY"
#     MOTOR_VEHICLE_SUPPLIES = "MOTOR_VEHICLE_SUPPLIES"
#     OFFICE_AND_COMMERCIAL = "OFFICE_AND_COMMERCIAL"
#     CONSTRUCTION_MATERIALS_NOT = "CONSTRUCTION_MATERIALS_NOT"
#     OFFICE_PHOTOGRAPHIC_PHOTOCOPY = "OFFICE_PHOTOGRAPHIC_PHOTOCOPY"
#     COMPUTERS_COMPUTER_PERIPHERAL = "COMPUTERS_COMPUTER_PERIPHERAL"
#     COMMERCIAL_EQUIPMENT_NOT = "COMMERCIAL_EQUIPMENT_NOT"
#     MEDICAL_DENTAL_OPHTHALMIC = "MEDICAL_DENTAL_OPHTHALMIC"
#     METAL_SERVICE_CENTERS = "METAL_SERVICE_CENTERS"
#     ELECTRICAL_PARTS_AND = "ELECTRICAL_PARTS_AND"
#     HARDWARE_EQUIPMENT_AND = "HARDWARE_EQUIPMENT_AND"
#     PLUMBING_AND_HEATING = "PLUMBING_AND_HEATING"
#     INDUSTRIAL_SUPPLIES_NOT = "INDUSTRIAL_SUPPLIES_NOT"
#     PRECIOUS_STONES_AND = "PRECIOUS_STONES_AND"
#     DURABLE_GOODS_NOT = "DURABLE_GOODS_NOT"
#     STATIONERY_OFFICE_SUPPLIES = "STATIONERY_OFFICE_SUPPLIES"
#     DRUGS_DRUG_PROPRIETORS = "DRUGS_DRUG_PROPRIETORS"
#     PIECE_GOODS_NOTIONS = "PIECE_GOODS_NOTIONS"
#     MENS_WOMENS_AND = "MENS_WOMENS_AND"
#     COMMERCIAL_FOOTWEAR = "COMMERCIAL_FOOTWEAR"
#     CHEMICALS_AND_ALLIED = "CHEMICALS_AND_ALLIED"
#     PETROLEUM_AND_PETROLEUM = "PETROLEUM_AND_PETROLEUM"
#     BOOKS_PERIODICALS_AND = "BOOKS_PERIODICALS_AND"
#     FLORISTS_SUPPLIES_NURSERY = "FLORISTS_SUPPLIES_NURSERY"
#     PAINTS_VARNISHES_AND = "PAINTS_VARNISHES_AND"
#     NON_DURABLE_GOODS = "NON_DURABLE_GOODS"
#     HOME_SUPPLY_WAREHOUSE = "HOME_SUPPLY_WAREHOUSE"
#     LUMBER_AND_BUILDING = "LUMBER_AND_BUILDING"
#     GLASS_PAINT_AND = "GLASS_PAINT_AND"
#     HARDWARE_STORES = "HARDWARE_STORES"
#     NURSERIES_LAWN = "NURSERIES_LAWN"
#     MOBILE_HOME_DEALERS = "MOBILE_HOME_DEALERS"
#     WHOLESALE_CLUBS = "WHOLESALE_CLUBS"
#     DUTY_FREE_STORE = "DUTY_FREE_STORE"
#     DISCOUNT_STORES = "DISCOUNT_STORES"
#     DEPARTMENT_STORES = "DEPARTMENT_STORES"
#     VARIETY_STORES = "VARIETY_STORES"
#     MISC_GENERAL_MERCHANDISE = "MISC_GENERAL_MERCHANDISE"
#     GROCERY_STORES_SUPERMARKETS = "GROCERY_STORES_SUPERMARKETS"
#     MEAT_PROVISIONERS = "MEAT_PROVISIONERS"
#     CANDY_NUT_AND = "CANDY_NUT_AND"
#     DAIRY_PRODUCTS_STORES = "DAIRY_PRODUCTS_STORES"
#     BAKERIES = "BAKERIES"
#     MISC_FOOD_STORES = "MISC_FOOD_STORES"
#     CAR_AND_TRUCK = "CAR_AND_TRUCK"
#     AUTOMOBILE_AND_TRUCK = "AUTOMOBILE_AND_TRUCK"
#     AUTOMOBILE_SUPPLY_STORES = "AUTOMOBILE_SUPPLY_STORES"
#     AUTOMOTIVE_TIRE_STORES = "AUTOMOTIVE_TIRE_STORES"
#     AUTOMOTIVE_PARTS_ACCESSORIES = "AUTOMOTIVE_PARTS_ACCESSORIES"
#     SERVICE_STATIONS = "SERVICE_STATIONS"
#     AUTOMATED_FUEL_DISPENSERS = "AUTOMATED_FUEL_DISPENSERS"
#     BOAT_DEALERS = "BOAT_DEALERS"
#     RECREATIONAL_AND_UTILITY = "RECREATIONAL_AND_UTILITY"
#     MOTORCYCLE_DEALERS = "MOTORCYCLE_DEALERS"
#     MOTOR_HOME_DEALERS = "MOTOR_HOME_DEALERS"
#     SNOWMOBILE_DEALERS = "SNOWMOBILE_DEALERS"
#     MISCELLANEOUS_AUTO_DEALERS = "MISCELLANEOUS_AUTO_DEALERS"
#     MENS_AND_BOYS = "MENS_AND_BOYS"
#     WOMENS_READY_TO = "WOMENS_READY_TO"
#     WOMENS_ACCESSORY_AND = "WOMENS_ACCESSORY_AND"
#     CHILDRENS_AND_INFANTS = "CHILDRENS_AND_INFANTS"
#     FAMILY_CLOTHING_STORES = "FAMILY_CLOTHING_STORES"
#     SPORTS_APPAREL_RIDING = "SPORTS_APPAREL_RIDING"
#     SHOE_STORES = "SHOE_STORES"
#     FURRIERS_AND_FUR = "FURRIERS_AND_FUR"
#     MENS_AND_WOMENS = "MENS_AND_WOMENS"
#     TAILORS_SEAMSTRESS_MENDING = "TAILORS_SEAMSTRESS_MENDING"
#     WIG_AND_TOUPEE = "WIG_AND_TOUPEE"
#     MISCELLANEOUS_APPAREL_AND = "MISCELLANEOUS_APPAREL_AND"
#     FURNITURE_HOME_FURNISHINGS = "FURNITURE_HOME_FURNISHINGS"
#     FLOOR_COVERING_STORES = "FLOOR_COVERING_STORES"
#     DRAPERY_WINDOW_COVERING = "DRAPERY_WINDOW_COVERING"
#     FIREPLACE_FIREPLACE_SCREENS = "FIREPLACE_FIREPLACE_SCREENS"
#     MISCELLANEOUS_HOME_FURNISHING = "MISCELLANEOUS_HOME_FURNISHING"
#     HOUSEHOLD_APPLIANCE_STORES = "HOUSEHOLD_APPLIANCE_STORES"
#     ELECTRONIC_SALES = "ELECTRONIC_SALES"
#     MUSIC_STORES_MUSICAL = "MUSIC_STORES_MUSICAL"
#     COMPUTER_SOFTWARE_STORES = "COMPUTER_SOFTWARE_STORES"
#     RECORD_SHOPS = "RECORD_SHOPS"
#     CATERERS = "CATERERS"
#     EATING_PLACES_AND = "EATING_PLACES_AND"
#     DRINKING_PLACES_ALCOHOLIC = "DRINKING_PLACES_ALCOHOLIC"
#     FAST_FOOD_RESTAURANTS = "FAST_FOOD_RESTAURANTS"
#     DIGITAL_GOODS_MEDIA = "DIGITAL_GOODS_MEDIA"
#     DIGITAL_GOODS_GAMES = "DIGITAL_GOODS_GAMES"
#     DIGITAL_GOODS_APPLICATIONS = "DIGITAL_GOODS_APPLICATIONS"
#     DIGITAL_GOODS_LARGE = "DIGITAL_GOODS_LARGE"
#     DRUG_STORES_AND = "DRUG_STORES_AND"
#     PACKAGE_STORES = "PACKAGE_STORES"
#     USED_MERCHANDISE_AND = "USED_MERCHANDISE_AND"
#     ANTIQUE_SHOPS = "ANTIQUE_SHOPS"
#     PAWN_SHOPS_AND = "PAWN_SHOPS_AND"
#     WRECKING_AND_SALVAGE = "WRECKING_AND_SALVAGE"
#     ANTIQUE_REPRODUCTIONS = "ANTIQUE_REPRODUCTIONS"
#     BICYCLE_SHOPS = "BICYCLE_SHOPS"
#     SPORTING_GOODS_STORES = "SPORTING_GOODS_STORES"
#     BOOK_STORES = "BOOK_STORES"
#     STATIONERY_STORES_OFFICE = "STATIONERY_STORES_OFFICE"
#     WATCH_CLOCK_JEWELRY = "WATCH_CLOCK_JEWELRY"
#     HOBBY_TOY_AND = "HOBBY_TOY_AND"
#     CAMERA_AND_PHOTOGRAPHIC = "CAMERA_AND_PHOTOGRAPHIC"
#     CARD_SHOPS_GIFT = "CARD_SHOPS_GIFT"
#     LEATHER_GOODS_STORES = "LEATHER_GOODS_STORES"
#     SEWING_NEEDLE_FABRIC = "SEWING_NEEDLE_FABRIC"
#     GLASSWARE_CRYSTAL_STORES = "GLASSWARE_CRYSTAL_STORES"
#     DIRECT_MARKETING = "DIRECT_MARKETING"
#     MAIL_ORDER_HOUSES = "MAIL_ORDER_HOUSES"
#     DOOR_TO_DOOR = "DOOR_TO_DOOR"
#     ARTISTS_SUPPLY_AND = "ARTISTS_SUPPLY_AND"
#     ART_DEALERS_AND = "ART_DEALERS_AND"
#     STAMP_AND_COIN = "STAMP_AND_COIN"
#     RELIGIOUS_GOODS_STORES = "RELIGIOUS_GOODS_STORES"
#     HEARING_AIDS = "HEARING_AIDS"
#     ORTHOPEDIC_GOODS_PROSTHETIC = "ORTHOPEDIC_GOODS_PROSTHETIC"
#     COSMETIC_STORES = "COSMETIC_STORES"
#     TYPEWRITER_STORES = "TYPEWRITER_STORES"
#     FUEL_FUEL = "FUEL_FUEL"
#     FLORISTS = "FLORISTS"
#     CIGAR_STORES_AND = "CIGAR_STORES_AND"
#     NEWS_DEALERS_AND = "NEWS_DEALERS_AND"
#     PET_SHOPS_PET = "PET_SHOPS_PET"
#     SWIMMING_POOLS = "SWIMMING_POOLS"
#     ELECTRIC_RAZOR_STORES = "ELECTRIC_RAZOR_STORES"
#     TENT_AND_AWNING = "TENT_AND_AWNING"
#     MISCELLANEOUS_AND_SPECIALTY = "MISCELLANEOUS_AND_SPECIALTY"
#     FINANCIAL_INSTITUTIONS = "FINANCIAL_INSTITUTIONS"
#     NON_FINANCIAL_INSTITUTIONS = "NON_FINANCIAL_INSTITUTIONS"
#     SECURITY_BROKERS_DEALERS = "SECURITY_BROKERS_DEALERS"
#     INSURANCE_SALES_UNDERWRITING = "INSURANCE_SALES_UNDERWRITING"
#     INSURANCE_PREMIUMS_NO = "INSURANCE_PREMIUMS_NO"
#     INSURANCE_NOT_ELSEWHERE = "INSURANCE_NOT_ELSEWHERE"
#     REAL_ESTATE_AGENTS = "REAL_ESTATE_AGENTS"
#     LODGING_HOTELS = "LODGING_HOTELS"
#     TIMESHARES = "TIMESHARES"
#     SPORTING_AND_RECREATIONAL = "SPORTING_AND_RECREATIONAL"
#     TRAILER_PARKS_AND = "TRAILER_PARKS_AND"
#     LAUNDRY_CLEANING_AND = "LAUNDRY_CLEANING_AND"
#     LAUNDRY_FAMILY = "LAUNDRY_FAMILY"
#     DRY_CLEANERS = "DRY_CLEANERS"
#     CARPET_AND_UPHOLSTERY = "CARPET_AND_UPHOLSTERY"
#     PHOTOGRAPHIC_STUDIOS = "PHOTOGRAPHIC_STUDIOS"
#     BARBER_AND_BEAUTY = "BARBER_AND_BEAUTY"
#     SHOP_REPAIR_SHOPS = "SHOP_REPAIR_SHOPS"
#     FUNERAL_SERVICE_AND = "FUNERAL_SERVICE_AND"
#     DATING_AND_ESCORT = "DATING_AND_ESCORT"
#     TAX_PREPARATION_SERVICE = "TAX_PREPARATION_SERVICE"
#     COUNSELING_SERVICE = "COUNSELING_SERVICE"
#     BUYING_SHOPPING_SERVICES_CLUBS = "BUYING_SHOPPING_SERVICES_CLUBS"
#     CLOTHING_RENTAL = "CLOTHING_RENTAL"
#     MASSAGE_PARLORS = "MASSAGE_PARLORS"
#     HEALTH_AND_BEAUTY = "HEALTH_AND_BEAUTY"
#     MISCELLANEOUS_PERSONAL_SERVICES = "MISCELLANEOUS_PERSONAL_SERVICES"
#     ADVERTISING_SERVICES = "ADVERTISING_SERVICES"
#     CONSUMER_CREDIT_REPORTING = "CONSUMER_CREDIT_REPORTING"
#     BLUEPRINTING_AND_PHOTOCOPYING = "BLUEPRINTING_AND_PHOTOCOPYING"
#     COMMERCIAL_PHOTOGRAPHY_ART = "COMMERCIAL_PHOTOGRAPHY_ART"
#     QUICK_COPY_REPRODUCTION = "QUICK_COPY_REPRODUCTION"
#     STENOGRAPHIC_AND_SECRETARIAL = "STENOGRAPHIC_AND_SECRETARIAL"
#     EXTERMINATING_AND_DISINFECTING = "EXTERMINATING_AND_DISINFECTING"
#     CLEANING_AND_MAINTENANCE = "CLEANING_AND_MAINTENANCE"
#     EMPLOYMENT_AGENCIES_TEMPORARY = "EMPLOYMENT_AGENCIES_TEMPORARY"
#     COMPUTER_PROGRAMMING_INTEGRATED = "COMPUTER_PROGRAMMING_INTEGRATED"
#     INFORMATION_RETRIEVAL_SERVICES = "INFORMATION_RETRIEVAL_SERVICES"
#     COMPUTER_MAINTENANCE_AND = "COMPUTER_MAINTENANCE_AND"
#     MANAGEMENT_CONSULTING_AND = "MANAGEMENT_CONSULTING_AND"
#     PROTECTIVE_AND_SECURITY = "PROTECTIVE_AND_SECURITY"
#     EQUIPMENT_RENTAL_AND = "EQUIPMENT_RENTAL_AND"
#     PHOTOFINISHING_LABORATORIES_PHOTO = "PHOTOFINISHING_LABORATORIES_PHOTO"
#     BUSINESS_SERVICES_NOT = "BUSINESS_SERVICES_NOT"
#     TRUCK_STOP = "TRUCK_STOP"
#     CAR_RENTAL_COMPANIES = "CAR_RENTAL_COMPANIES"
#     TRUCK_AND_UTILITY = "TRUCK_AND_UTILITY"
#     MOTOR_HOME_AND = "MOTOR_HOME_AND"
#     AUTOMOBILE_PARKING_LOTS = "AUTOMOBILE_PARKING_LOTS"
#     AUTOMOTIVE_BODY_REPAIR = "AUTOMOTIVE_BODY_REPAIR"
#     TIRE_RE_TREADING = "TIRE_RE_TREADING"
#     PAINT_SHOPS = "PAINT_SHOPS"
#     AUTOMOTIVE_SERVICE_SHOPS = "AUTOMOTIVE_SERVICE_SHOPS"
#     CAR_WASHES = "CAR_WASHES"
#     TOWING_SERVICES = "TOWING_SERVICES"
#     RADIO_REPAIR_SHOPS = "RADIO_REPAIR_SHOPS"
#     AIR_CONDITIONING_AND = "AIR_CONDITIONING_AND"
#     ELECTRICAL_AND_SMALL = "ELECTRICAL_AND_SMALL"
#     WATCH_CLOCK_AND = "WATCH_CLOCK_AND"
#     FURNITURE_FURNITURE_REPAIR = "FURNITURE_FURNITURE_REPAIR"
#     WELDING_REPAIR = "WELDING_REPAIR"
#     REPAIR_SHOPS_AND = "REPAIR_SHOPS_AND"
#     GOVERNMENT_OWNED_LOTTERIES = "GOVERNMENT_OWNED_LOTTERIES"
#     GOVERNMENT_LICENSED_ON = "GOVERNMENT_LICENSED_ON"
#     GOVERNMENT_LICENSED_HORSE_DOG = "GOVERNMENT_LICENSED_HORSE_DOG"
#     MOTION_PICTURES_AND = "MOTION_PICTURES_AND"
#     MOTION_PICTURE_THEATERS = "MOTION_PICTURE_THEATERS"
#     VIDEO_TAPE_RENTAL = "VIDEO_TAPE_RENTAL"
#     DANCE_HALLS_STUDIOS = "DANCE_HALLS_STUDIOS"
#     THEATRICAL_PRODUCERS_EXCEPT = "THEATRICAL_PRODUCERS_EXCEPT"
#     BANDS_ORCHESTRAS_AND = "BANDS_ORCHESTRAS_AND"
#     BILLIARD_AND_POOL = "BILLIARD_AND_POOL"
#     BOWLING_ALLEYS = "BOWLING_ALLEYS"
#     COMMERCIAL_SPORTS_ATHLETIC = "COMMERCIAL_SPORTS_ATHLETIC"
#     TOURIST_ATTRACTIONS_AND = "TOURIST_ATTRACTIONS_AND"
#     GOLF_COURSES = "GOLF_COURSES"
#     VIDEO_AMUSEMENT_GAME = "VIDEO_AMUSEMENT_GAME"
#     VIDEO_GAME_ARCADES_ESTABLISHMENTS = "VIDEO_GAME_ARCADES_ESTABLISHMENTS"
#     BETTING_INCLUDING_LOTTERY = "BETTING_INCLUDING_LOTTERY"
#     AMUSEMENT_PARKS_CARNIVALS = "AMUSEMENT_PARKS_CARNIVALS"
#     MEMBERSHIP_CLUBS_SPORTS = "MEMBERSHIP_CLUBS_SPORTS"
#     AQUARIUMS_SEA_AQUARIUMS = "AQUARIUMS_SEA_AQUARIUMS"
#     RECREATION_SERVICES_NOT = "RECREATION_SERVICES_NOT"
#     DOCTORS_AND_PHYSICIANS = "DOCTORS_AND_PHYSICIANS"
#     DENTISTS_AND_ORTHODONTISTS = "DENTISTS_AND_ORTHODONTISTS"
#     OSTEOPATHS = "OSTEOPATHS"
#     CHIROPRACTORS = "CHIROPRACTORS"
#     OPTOMETRISTS_AND_OPHTHALMOLOGISTS = "OPTOMETRISTS_AND_OPHTHALMOLOGISTS"
#     OPTICIANS_OPTICIANS_GOODS = "OPTICIANS_OPTICIANS_GOODS"
#     OPTICIANS_OPTICAL_GOODS = "OPTICIANS_OPTICAL_GOODS"
#     PODIATRISTS_AND_CHIROPODISTS = "PODIATRISTS_AND_CHIROPODISTS"
#     NURSING_AND_PERSONAL = "NURSING_AND_PERSONAL"
#     HOSPITALS = "HOSPITALS"
#     MEDICAL_AND_DENTAL = "MEDICAL_AND_DENTAL"
#     MEDICAL_SERVICES_AND = "MEDICAL_SERVICES_AND"
#     LEGAL_SERVICES_AND = "LEGAL_SERVICES_AND"
#     ELEMENTARY_AND_SECONDARY = "ELEMENTARY_AND_SECONDARY"
#     COLLEGES_JUNIOR_COLLEGES = "COLLEGES_JUNIOR_COLLEGES"
#     CORRESPONDENCE_SCHOOLS = "CORRESPONDENCE_SCHOOLS"
#     BUSINESS_AND_SECRETARIAL = "BUSINESS_AND_SECRETARIAL"
#     VOCATIONAL_SCHOOLS_AND = "VOCATIONAL_SCHOOLS_AND"
#     SCHOOLS_AND_EDUCATIONAL = "SCHOOLS_AND_EDUCATIONAL"
#     CHILD_CARE_SERVICES = "CHILD_CARE_SERVICES"
#     CHARITABLE_AND_SOCIAL = "CHARITABLE_AND_SOCIAL"
#     CIVIC_FRATERNAL_AND = "CIVIC_FRATERNAL_AND"
#     POLITICAL_ORGANIZATIONS = "POLITICAL_ORGANIZATIONS"
#     RELIGIOUS_ORGANIZATIONS = "RELIGIOUS_ORGANIZATIONS"
#     AUTOMOBILE_ASSOCIATIONS = "AUTOMOBILE_ASSOCIATIONS"
#     MEMBERSHIP_ORGANIZATIONS = "MEMBERSHIP_ORGANIZATIONS"
#     TESTING_LABORATORIES = "TESTING_LABORATORIES"
#     ARCHITECTURAL_ENGINEERING = "ARCHITECTURAL_ENGINEERING"
#     ACCOUNTING_AUDITING_AND = "ACCOUNTING_AUDITING_AND"
#     PROFESSIONAL_SERVICES = "PROFESSIONAL_SERVICES"
#     COURT_COSTS_INCLUDING = "COURT_COSTS_INCLUDING"
#     FINES = "FINES"
#     BAIL_AND_BOND = "BAIL_AND_BOND"
#     TAX_PAYMENTS = "TAX_PAYMENTS"
#     GOVERNMENT_SERVICES = "GOVERNMENT_SERVICES"
#     POSTAL_SERVICES = "POSTAL_SERVICES"
#     INTRA_GOVERNMENT = "INTRA_GOVERNMENT"
#     AUTOMATED_REFERRAL_SERVICE = "AUTOMATED_REFERRAL_SERVICE"
#     VISA_CREDENTIAL_SERVICE = "VISA_CREDENTIAL_SERVICE"
#     GCAS_EMERGENCY_SERVICES = "GCAS_EMERGENCY_SERVICES"
#     INTRA_COMPANY = "INTRA_COMPANY"
#
#     @classmethod
#     def get_category(cls, mcc_category: str):
#         category = getattr(MCCCategories, mcc_category, None)
#         if category is None:
#             raise MCCCategoryNotFound(f"There is no category for -> {mcc_category}")
#
#         return category
#
#
# class MCCCategoryNotFound(Exception):
#     pass
