version: "3.8"


services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    env_file:
      - .env.prod
    expose:
      - 5432
    ports:
      - 127.0.0.1:${POSTGRES_PORT-5432}:5432
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A money_manager.celery.app worker -l info
    env_file:
      - .env.prod
    volumes:
      - ./:/opt/money_manager_bot:ro
      - ./:/opt/money_manager_bot
    depends_on:
      - web

  beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env.prod
    command: celery -A money_manager.celery.app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - web

  web:
    expose:
      - 8000
#      - 443
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
#      - "443:443"
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - /etc/letsencrypt/live/osprey.work.gd/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/osprey.work.gd/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - ./:/opt/money_manager_bot:ro
      - ./:/opt/money_manager_bot
    restart: always
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.0.7-alpine
    volumes:
      - ./redis:/data
    environment:
      - REDIS_BIND=127.0.0.1
    ports:
        - 127.0.0.1:${REDIS_PORT-6379}:6379
    restart: always

volumes:
  postgres-data:
