version: "3.8"


services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB-db}
      POSTGRES_USER: ${POSTGRES_USER-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT-54322}:5432

  web:
    expose:
      - 8000
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env.dev
    environment:
      APP_POSTGRES__URL: ${APP_POSTGRES__URL}
      APP_DSN: ${APP_DSN}
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      APP_MONOBANK__BASE_URL: ${APP_MONOBANK__BASE_URL}
      APP_WALLETAPP__BASE_URL: ${APP_WALLETAPP__BASE_URL}
      APP_BOT_CONF__DEFAULT_TOKEN: ${APP_BOT_CONF__DEFAULT_TOKEN}
      APP_REDIS__URL: ${APP_REDIS__URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.0.7-alpine
    volumes:
      - ./redis:/data
    ports:
      - ${REDIS_PORT-6379}:6379

volumes:
  postgres-data:
