import enum


class TransactionStatus(str, enum.Enum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    AWAITING_ADD_COMMENT = "AWAITING_ADD_COMMENT"
    ADD_COMMENT = "ADD_COMMENT"
    AWAITING_UPDATE_PRICE = "AWAITING_UPDATE_PRICE"
    UPDATE_PRICE = "UPDATE_PRICE"
    IDLE = "IDLE"
