# Generated by Django 4.0.3 on 2022-04-21 07:38
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ("tbot_base", "0004_alter_botusers_user_id"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="botusers",
            name="user_id",
            field=models.CharField(blank=True, default="None", max_length=30, verbose_name="User id"),
        ),
    ]
