# Generated by Django 4.0.3 on 2022-04-21 08:41
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        (
            "tbot_base",
            "0007_alter_botusers_first_name_alter_botusers_last_name_and_more",
        ),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="botusers",
            name="first_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=50,
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="last_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=50,
                verbose_name="Last name",
            ),
        ),
    ]
