# Generated by Django 5.0.4 on 2024-04-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0012_remove_botusers_free_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, max_length=30, verbose_name='User id')),
                ('monobank_token', models.CharField(max_length=256, verbose_name='Monobank Token')),
                ('wallet_app_password', models.CharField(max_length=256, verbose_name='Monobank Token')),
                ('wallet_app_login', models.CharField(max_length=100, verbose_name='Monobank Token')),
            ],
            options={
                'verbose_name': 'User Integrations',
                'verbose_name_plural': 'Users Integrations',
            },
        ),
    ]
