# Generated by Django 5.0.4 on 2024-05-02 07:30
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ("tbot_base", "0013_userintegrations"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="botusers",
            name="chat_id",
            field=models.CharField(
                default=0, editable=False, max_length=30, verbose_name="Chat id"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userintegrations",
            name="monobank_token",
            field=models.CharField(max_length=256, verbose_name="Monobank Token"),
        ),
        migrations.AlterField(
            model_name="userintegrations",
            name="wallet_app_login",
            field=models.CharField(max_length=256, verbose_name="WalletApp Login"),
        ),
        migrations.AlterField(
            model_name="userintegrations",
            name="wallet_app_password",
            field=models.CharField(max_length=256, verbose_name="WalletApp Password"),
        ),
    ]
