# Generated by Django 5.0.6 on 2024-05-19 13:32
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ("tbot_base", "0014_botusers_chat_id_and_more"),
    ]

    operations: ClassVar = [
        migrations.RemoveField(
            model_name="userintegrations",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="userpayments",
            name="user_id",
        ),
        migrations.AddField(
            model_name="userintegrations",
            name="user",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration",
                to="tbot_base.botusers",
                verbose_name="User"
            ),
        ),
        migrations.AddField(
            model_name="userpayments",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="tbot_base.botusers",
                verbose_name="User"
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="user_id",
            field=models.CharField(
                editable=False,
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="User id"
            ),
        ),
    ]
