# Generated by Django 5.0.6 on 2024-05-19 18:58
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ("tbot_base", "0015_remove_userintegrations_user_id_and_more"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="userintegrations",
            name="monobank_token",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Monobank Token"
            ),
        ),
        migrations.AlterField(
            model_name="userintegrations",
            name="wallet_app_login",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="WalletApp Login"
            ),
        ),
        migrations.AlterField(
            model_name="userintegrations",
            name="wallet_app_password",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="WalletApp Password"
            ),
        ),
    ]
