# Generated by Django 5.0.6 on 2024-05-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbot_base", "0016_alter_userintegrations_monobank_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userintegrations",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="tbot_base.botusers",
                verbose_name="User",
            ),
        ),
    ]
