# Generated by Django 5.0.6 on 2024-05-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbot_base", "0017_alter_userintegrations_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userintegrations",
            name="monobank_token",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                unique=True,
                verbose_name="Monobank Token",
            ),
        ),
    ]
