# Generated by Django 5.0.6 on 2024-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbot_base", "0018_alter_userintegrations_monobank_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userintegrations",
            name="wallet_app_login",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                unique=True,
                verbose_name="WalletApp Login",
            ),
        ),
    ]
