# Generated by Django 5.0.6 on 2024-12-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbot_base", "0019_alter_userintegrations_wallet_app_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWalletLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_id",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        unique=True,
                        verbose_name="Label ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Label name"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="tbot_base.botusers",
                        verbose_name="Label",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Wallet Label",
                "verbose_name_plural": "User Wallet Labels",
            },
        ),
    ]
