# Generated by Django 5.0.6 on 2024-12-03 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbot_base", "0020_userwalletlabel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwalletlabel",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="tbot_base.botusers",
                verbose_name="User",
            ),
        ),
    ]
