# Generated by Django 5.1.5 on 2025-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbot_base", "0021_alter_userwalletlabel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userintegrations",
            name="wallet_app_login",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="WalletApp Login"
            ),
        ),
        migrations.AlterField(
            model_name="userwalletlabel",
            name="label_id",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Label ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="userwalletlabel",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_label_name"
            ),
        ),
    ]
