# Generated by Django 5.1.5 on 2025-05-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbot_base", "0022_alter_userintegrations_wallet_app_login_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.CharField(max_length=256, verbose_name="Category ID"),
                ),
                (
                    "category_type",
                    models.CharField(max_length=256, verbose_name="Category type"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Category name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="tbot_base.botusers",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Category",
                "verbose_name_plural": "User Categories",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category_id", "category_type"),
                        name="unique_user_category_id_category_type",
                    )
                ],
            },
        ),
    ]
