# Generated by Django 5.1.5 on 2025-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbot_base", "0023_usercategories"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usercategories",
            name="unique_user_category_id_category_type",
        ),
        migrations.RemoveField(
            model_name="usercategories",
            name="category_type",
        ),
        migrations.AddConstraint(
            model_name="usercategories",
            constraint=models.UniqueConstraint(
                fields=("user", "category_id"), name="unique_user_category_id"
            ),
        ),
    ]
