# Generated by Django 5.1.5 on 2025-05-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tbot_base",
            "0024_remove_usercategories_unique_user_category_id_category_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTransactions",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "doc_id",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Memory Doc ID"
                    ),
                ),
                (
                    "body",
                    models.JSONField(default=dict, verbose_name="Transaction Body"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="tbot_base.botusers",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Transaction",
                "verbose_name_plural": "User Transactions",
            },
        ),
    ]
