import enum


class UserStates(enum.Enum):
    IDLE = 0
    AWAITING_MONOTOKEN = 1
    AWAITING_WALLETAPP_USERNAME = 2
    AWAITING_WALLETAPP_PASSWORD = 3
    WRITE_TRANSACTION = 4


class CredentialType(str, enum.Enum):
    MONO_TOKEN = "MONO_TOKEN"  # NOQA
    WALLETAPP_USERNAME = "WALLETAPP_USERNAME"
    WALLETAPP_PASSWORD = "WALLETAPP_PASSWORD" # NOQA
