import enum


class UserStates(enum.Enum):
    IDLE = 0
    AWAITING_MONOTOKEN = 1
    AWAITING_WALLETAPP_USERNAME = 2
    AWAITING_WALLETAPP_PASSWORD = 3
    WRITE_TRANSACTION = 4
    RESET_MONOTOKEN = 5
    RESET_WALLETAPP_PASSWORD = 6
    AWAITING_ADDITIONAL_MONOTOKEN = 7
